### ISSUE TITLE
BUFR sequence for GBON surface hourly data

### ISSUE THREAD

**Issue by efucile** [wmo-im/BUFR4#107]
# Branch

Add when created. 

# Summary and purpose

GBON implementation requires the exchange of surface hourly data. There is the need to identify which sequence, if available, or develop a new sequence for surface hourly data. There is also the need to provide observing practises in support of this sequence.

# Stakeholders

include as appropriate

# Action proposed

Enter text.

# Discussions

Requirements and purposes of the proposal along with other background information, which could be included in the SUMMARY OF MEETING REPORT.

# Detailed proposal

Keeps details up to date as decisions are finalized.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-16.3.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-16.3.2022)

Need to have small team to look at this. 

1.  Need to identify the changes in the regulations; this will be presented to INFCOM in October 2022
2.  Identify and/or create new template

**Comment by amilan17** [comment]
first small group: @marijanacrepulja @marianmajan-ibl @SibylleK @efucile

**Comment by amilan17** [comment]
This may be a useful reference for determing what kinds of GBON data need to be considered: https://meetings.wmo.int/Cg-Ext-2021/_layouts/15/WopiFrame.aspx?sourcedoc=/Cg-Ext-2021/InformationDocuments/Cg-Ext(2021)-INF04-1-CATALOGUE-OF-CORE-DATA_en.docx&action=default

**Comment by efucile** [comment]
Hello everyone,
this is ahead of our meeting tomorrow. 
We have GBON requirements here
[GBON_Requirements.docx](https://github.com/wmo-im/BUFR4/files/8325859/GBON_Requirements.docx)

See you tomorrow
Enrico

**Comment by efucile** [comment]
307096 explained 
[GBON_Requirements.docx](https://github.com/wmo-im/BUFR4/files/8461198/GBON_Requirements.docx)

**Comment by efucile** [comment]
**Meeting 11-4-2022**

**Discussion**
1. Which sequence? The sequence 307096 is a merge of 307080 (SYNOP) and 307091 (AWS). The team considers the sequence to be the best fit for GBON hourly data. Etienne clarified that GBON is requiring hourly data, but RBON requires more frequent data. It was agreed that 307096 could be used for sub-hourly data, but Sibylle clarified that 307092 (n-minutes template) is used by Eumetnet for sub-hourly data. We may have the need to introduce that template for RBON. Enrico suggested collecting the requirements for the various templates in a table to be able in the future to document it for the private companies producing data from the stations. Enrico informed the team that there is ongoing work to develop a GeoJSON schema to be used for communication from the station to a collection point where the conversion will be performed. The aim is to lower the barriers for equipment manufacturers.
2. In which part of the MoC Vol. I.2 are we inserting the required provisions? Enrico highlighted that Part C title is more on mapping alphanumeric codes to BUFR and is not the right place for WIGOS provisions. The team discussed possible options and Sibylle highlighted that the content of PART C is very useful and to be used also for GBON. It was decided to make a new Part and to make reference to Part C if required. Part D we need to find a good title. Part D will contain GBON.

**Decisions**

1. sequence 307096 is ok for GBON
2. new Part D to be added to MoC for WIGOS

**Actions**

- [ ] provide a table with all the sequences for the team to add known uses and motivation (@efucile)
- [ ] provide an initial draft of Part D (@efucile)

**Comment by efucile** [comment]
Hello everyone,
here is the table as per action 
[surface_land_sequences.xlsx](https://github.com/wmo-im/BUFR4/files/8553624/surface_land_sequences.xlsx)
@marianmajan-ibl @marijanacrepulja @SibylleK, please download, fill in the third column, and send me via email?
Thanks

**Comment by efucile** [comment]
Some more work from my side. Here is the first draft of Part D. 
[PART D 306_I2_2019_updated_2021_en-3.docx](https://github.com/wmo-im/BUFR4/files/8562283/PART.D.306_I2_2019_updated_2021_en-3.docx)

**Comment by efucile** [comment]
filecloud document https://filecloud.wmo.int/share/page/site/gbon-bufr/document-details?nodeRef=workspace://SpacesStore/ceb12f97-78d9-4818-a58f-fdaaddbe534b

**Comment by amilan17** [comment]
@amilan17 - 

*   change name of 'geopotential height' to 'geopotential height of the standard level' (**0 10 009)**

**Comment by efucile** [comment]
> 

@amilan17 we don't need to change the name of the descriptor we need to change the text in the 3 07 096 template

**Comment by amilan17** [comment]
approved by INFCOM-2.
