### ISSUE TITLE
 Table B 01: New BUFR descriptor for light source identifier

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#109]
# Summary and purpose

ECMWF is proposing new BUFR descriptor for light source identifier. 

# Stakeholders

Marijana Crepulja, Antje Inness, Roberto Ribas (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for assimilation of Altius ozone observations. In order to identify different light sources we need a new descriptor. 

# Detailed proposal

**1. Add a new entry and corresponding note in the identification class of  table B  (0-01-145)  and a new code table to describe light source**

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-01-145 | Light source identifier| Numeric| 0 | -8 | 20

NOTE: Positive value corresponds to Hipparcos identifier, 0 is Sun, -2 is Venus, -4 is Mars, -5 is Jupiter, -6 is Saturn, -7 is Earth's moon, -8 is Bright limb

**Comment by amilan17** [comment]
Re: https://github.com/wmo-im/CCT/wiki/Teleconference-26-and-28.4.2022

<table><tbody><tr><td>In progress, discussion over new descriptor and meaning of the values. Marijana to add explanatory note, linking to the Hipparcos catalogue.</td></tr></tbody></table>

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

note is added in issue summary, change -7 to 'Earth's moon'

**Comment by amilan17** [comment]
@marijanacrepulja please add the note and use temporary note ID: issue109

https://github.com/wmo-im/BUFR4/blob/issue109/notes/BUFRCREX_TableB_notes.csv

**Comment by marijanacrepulja** [comment]
@amilan17 I have added the note. Not sure if it is correct way of doing it. Could you please review and move to "Ready to FT " I am happy to add changes if need be. Thanks

It would be good we go through the process of adding the note at the meeting next week, so we all agree and know it.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022) notes: 

@amilan17 validate for FT readiness

**Comment by amilan17** [comment]
@marijanacrepulja I made some note revisions, does it still make sense? 

"In descriptor 0 01 145, the positive values correspond to Hipparcos identifiers where 0 is Sun, -2 is Venus, -4 is Mars, -5 is Jupiter, -6 is Saturn, -7 is Earth's moon, and -8 is Bright limb."

**Comment by marijanacrepulja** [comment]
@amilan17 
"0 is Sun, -2 is Venus, -4 is Mars, -5 is Jupiter, -6 is Saturn, -7 is Earth's moon, and -8 is Bright limb" are not part of the Hipparcos identifiers. The Hipparcos Identifier is Star ID.
