### ISSUE TITLE
Code table 01: New BUFR codes for Retrieval identifier 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#111]
# Summary and purpose

ECMWF is proposing new BUFR codes in Retrieval identifier code table.

# Stakeholders

Angela Benedetti, Karen Henry, Marijana Crepulja (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for assimilation of aerosol observations from Aelous. In order to identify different retrievals new codes are needed in retrieval identifier code table

# Detailed proposal

1. Add new entries CODE TABLE 0-01-155 for Retrieval identifier

Code Figure |  Retrieval identifier
-- | --
0 | Standard Correct Algorithm (SCA)
1 | Standard Correct Algorithm mid-bin (SCA mid-bin)
2 | Maximum Likelihood Estimation (MLE)
3 | Optimal Estimation Profile (OE-PRO)
4 | Group
5 | Group mid-bin
6-254| Reserved
255| Missing

**Comment by amilan17** [comment]
re: [https://github.com/wmo-im/CCT/wiki/Teleconference-26-and-28.4.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-26-and-28.4.2022)

<table><tbody><tr><td>Discussion over name / text for new entry in code table (note also typo, Aelous -&gt; Aeolus). Marijana to consult with the data providers and whether the entry can be made more generic.</td></tr></tbody></table>

**Comment by marijanacrepulja** [comment]
@amilan17 can you please create branch for this issue. The discussion was over Aeolus Profile (AEL-PRO) entry. The feedback from data provider is still pending. I am thinking to withdraw that entry for time being and go forward with other entries.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022) notes: 

*   all are fine with OE-PRO; @amilan17 validate branch

**Comment by marijanacrepulja** [comment]
[AED-TN-CNRM-L2A-036--V2_0--2022_04_07.pdf](https://github.com/wmo-im/BUFR4/files/8879024/AED-TN-CNRM-L2A-036--V2_0--2022_04_07.pdf)
[AED-SD-CNRM-L2A-030--ATBD--v5_08-2021_07_09.pdf](https://github.com/wmo-im/BUFR4/files/8879027/AED-SD-CNRM-L2A-030--ATBD--v5_08-2021_07_09.pdf)

@amilan17 please find attached documentation regarding description of algorithms

**Comment by amilan17** [comment]
@marijanacrepulja I checked the documents and made the following changes. 

*   Maximum Likelihood ~Method~ Estimation (MLE)
*   mid bin ==> mid-bin
*   couldn't find any explicit text to check for for OE-PRO, group or group mid-bin

Can you please check the diff? (available just above this comment)

**Comment by marijanacrepulja** [comment]
@amilan17 thanks for updating the branch, I agree with changes 

OE-PRO is called AEL-PRO currently. The data provider made up the name OE-PRO based on the algorithm they used to calc it, to satisfy team's requirement for more generic name. It does not exist in documentation yet, but it will be included accordingly.

Please refer to pages 25, 30 for Group input fields

[AED-SD-DoRIT-L2A-025--IODD--v3_14--2022_02_14.pdf](https://github.com/wmo-im/BUFR4/files/8892192/AED-SD-DoRIT-L2A-025--IODD--v3_14--2022_02_14.pdf)
