### ISSUE TITLE
Code table 02: New BUFR code for TROPICS 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#112]
# Summary and purpose

ECMWF is proposing new BUFR codes in Satellite classification code table.

# Stakeholders

Niels Bormann, Marijana Crepulja (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for assimilation TROPICS observations . We would need new code in Satellite classification code table
to better indentify observations from TROPICS.

# Detailed proposal

1. Add new entries CODE TABLE 0-02-020 for Satellite classification

Code Figure |  Retrieval identifier
-- | --
251 | TROPICS

**Comment by amilan17** [comment]
@amilan17 create branch

**Comment by marijanacrepulja** [comment]
@amilan17 the branch is updated

**Comment by amilan17** [comment]
@marijanacrepulja - Can you please add the TROPICS acronym to this CSV: https://github.com/wmo-im/BUFR4/blob/issue112/notes/acronyms.csv

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated the branch by adding the TROPICS acronym
