### ISSUE TITLE
Code table 0 08 092 - Measurement uncertainty expression: New entry

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/BUFR4#113]
# Summary and purpose

DWD (Deutscher Wetterdienst) is proposing a new entry in Code table 0 08 092 – "Measurement uncertainty expression" for the representation of a “Combined Standard Uncertainty”* in order to offer an uncertainty information consisting of several components to the users of measurement data.

*see Guide to the expression of uncertainty in measurement (2008):  https://www.bipm.org/documents/20126/2071204/JCGM_100_2008_E.pdf/cb0ef43f-baa5-11cf-3f85-4dcd86f77bd6 , pp. 3 and 18-23 
 
# Stakeholders

DWD (Dr. Sven Brinckmann, Anna Klameth, Dr. Stefan Wacker), anyone willing to offer combined standard uncertainties for their measurements in BUFR format

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

The reporting of meteorological data needs to be accompanied by the provision of the accuracy / uncertainty / quality of the provided data value. A combined uncertainty information addresses the overall uncertainty due to different individual contributions (e.g. instruments, data acquisition, measurement itself, calibration). 
Since only the code table entry for “standard deviation” exists so far, we propose the introduction of a new entry for the complete uncertainty information. This new entry shall be named “combined standard uncertainty”.

# Detailed proposal

Add a new entry in Code table 0 08 092 - Measurement uncertainty expression

FXY|ElementName_en|CodeFigure|EntryName_en
--|--|--|--
008092|Measurement uncertainty expression|1|Combined standard uncertainty (see note 1)
008092|Measurement uncertainty expression|2-30|Reserved

(1) For determining combined standard uncertainty see Guide to the expression of uncertainty in measurement (2008), JCGM 100:2008. 
JCGM - Joint Committee for Guides in Metrology of BIPM - Bureau International de Poids et Mesures (https://www.bipm.org)

**Comment by SibylleK** [comment]
@amilan17, the branch is updated. I tried to include a note for the reference to BIPM, but I am not sure if it is ok to add the notes in the branches of the issues.

**Comment by amilan17** [comment]
@SibylleK I updated the note references. Do you think it's important to keep this in the note: "JCGM - Joint Committee for Guides in Metrology of BIPM - Bureau International de Poids et Mesures ([https://www.bipm.org](https://www.bipm.org/))"?

**Comment by amilan17** [comment]
@amilan17 put JCGM and BIPM in acronym table and upate note

**Comment by amilan17** [comment]
@SibylleK I updated the note and the acronym table. Will you please double check this commit: 2b3a4a0? thx!

**Comment by SibylleK** [comment]
@amilan17, Thank you very much, I double checked the commit.

**Comment by marijanacrepulja** [comment]
@SibylleK, @amilan17 many thanks for updates, branch is ready for FT

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-21.11.2022 notes: 
@marijanacrepulja will update branch, CGMS group approved
