### ISSUE TITLE
Code table 0 20 009 - General weather indicator (TAF/METAR): new entry NCD

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/BUFR4#114]
# Summary and purpose

A new entry NCD No clouds detected in Code table 0 20 009 - "General weather indicator (TAF/METAR)" is proposed.

# Stakeholders

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

In November 2005 the FM15/16 - METAR/SPECI were modified in the ICAO Annex 3 and the amendments were adopted to the Manual on Codes Volume I.1 Part A.
I.a. the abbreviation NCD for "when an automatic observing system is used and no clouds are detected by that system" was introduced.
But the suitable BUFR Code table was never amended accordingly.
NCD is now proposed as new entry in Code table 0 20 009.

# Detailed proposal

Add a new entry in Code table 0 20 009 - General weather indicator (TAF/METAR)

FXY|ElementName_en|CodeFigure|EntryName_en
--|--|--|--
020009|General weather indicator (TAF/METAR)|5|NCD No clouds detected
020009|General weather indicator (TAF/METAR)|6-14|Reserved

**Comment by SibylleK** [comment]
@amilan17, the branch is updated.

**Comment by marijanacrepulja** [comment]
@amilan17, the branch is updated accordingly, I have moved it to validated column. Please confirm branch validation and move to 'ready for FT'.
