### ISSUE TITLE
New BUFR template for CCI snow cover fraction

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#115]
# Summary and purpose

ECMWF is proposing new BUFR template for representing snow cover observations.

# Stakeholders

ECMWF

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for assimilation of snow cover observation from CCI. 

# Detailed proposal

**1. Add a new BUFR code in code table 008023**

CODE TABLE 0-08-023
0-08-023   First order statistic

Code Figure |  Retrieval identifier
-- | --
 14 | Root-mean-square error

**2. Add a new BUFR template for snow cover observations**

Table 			reference | Table 			references | Element 			name | Description 			/ comments
-- | -- | -- | --|
|3-12-062 |   | Snow cover | | |
||0 01 007 | Satellite identifier |    
||0 02 019 | Satellite instruments |   
||3 01 011 | Year, month, day |   
||3 01 013 | Hour, minute, second |    
||3 01 021 | Latitude/longitude (high accuracy) |   
||0 20 065 | Snow cover | |   
||0 08 023 | First order statistic |  
||0 20 065 | Snow cover |  | 
||0 08 023 | First order statistic

Keeps details up to date as decisions are finalized.

**Comment by amilan17** [comment]
@amilan17 create branch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

Marijana will provide sample file and sibylle will help with validation

**Comment by amilan17** [comment]
@marijanacrepulja Is there a note associated with 0 20 065?

**Comment by marijanacrepulja** [comment]
@amilan17 the note already exist. I have just put it as reminder. To avoid confusion I can remove it from proposal.

**Comment by amilan17** [comment]
@marijanacrepulja -- thanks. are you also updating the branch?

**Comment by SibylleK** [comment]
I have successfully decoded the example BUFR with the BUFR tables of this branch. 
The output is attached:
[cci_snow.bufr.DWD.txt.zip](https://github.com/wmo-im/BUFR4/files/8853841/cci_snow.bufr.DWD.txt.zip)

I checked the values of the first BUFR. Fortunately only the values of the latitude differ in the 7200 subsets. They are the same in both outputs (ecCodes and DWD BUFR reading software).

**Comment by marijanacrepulja** [comment]
Thanks very much @SibylleK!

@amilan17 branch has been updated, samples validated.  Could you please review and move to "Ready for FT"

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022) notes: ready to go
