### ISSUE TITLE
New BUFR descriptors to represent observations from TROPICS

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#117]
# Summary and purpose

ECMWF is proposing new BUFR descriptors for representing TROPICS observations.

# Stakeholders

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for operational assimilation of TROPICS observations. Therefore, we need a new BUFR descriptors to accommodate observation from TROPICS.

# Detailed proposal
**1. Add a new element  in table B 0-33-094 for TROPICS calibration quality flags**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-33-094 | Calibration quality control flags | Numeric| 0 | 0 | 24

**2. Add a new CODE/FLAG TABLE 0-33-094 for TROPICS calibration quality flags**
|Bit No| Calibration quality control flags | 
|----|-----|
| 1-15  |  Reserved | 
|16|  Non ocean|
|17| Lunar or Solar intrusion| 
|18| Spacecraft maneuver
|19| Cold calibration consistency| 
|20| Warm calibration consistency| 
|21|Descending 
|22| Night| 
|23| Payload rear orientation|
|All 24 | Missing| 

**3. Add a new table B descriptor 0-08-097 for Method used to calculate the average instrument temperature**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-08-097 | Method used to calculate the average instrument temperature| Numeric| 0 | 0 | 7

**4. Add a new CODE/FLAG TABLE 0-08-097 for Method used to calculate the average instrument temperature**
|Code|  Method used to calculate the average instrument temperature | 
|----|-----| 
|0| The average of six temperature sensors placed throughout the payload|
|1| Average of WF-band IFP and RFE sensors for channels 1 to 8
|2| Average of G-band RFE sensor for channels 9 to 12 |
|3-126| Reserved
|127| Missing value

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM, during our meeting in March we concluded that would be beneficial if we communicate new BUFR template for TROPICS with CGMS. Could you please ask for their feedback.  
@jbathegit could you please communicate new BUFR template for TROPICS with relevant colleagues on your side as well. As I am happy to take your comments on board.  
My colleagues from research have circulated BUFR template with relevant group, and they are satisfied with it.
Many thanks, Marijana

**Comment by jbathegit** [comment]
- What's the difference between the 3 different instrument temperatures that are being replicated using 1-01-003?  If you really want to report 3 different temperatures, then I think you need to add in a significance qualifier, or some other coordinate class descriptor within this replicated sequence in order to distinguish the difference between them.
- If you only have 12 channels, then why do you need to use an extended delayed descriptor replication factor?  In other words, why not use 0-31-001 (8-bits allowing for up to 255 replications) instead of 0-31-002 (16 bits allowing for up to 65535 replications)?

**Comment by marijanacrepulja** [comment]
Many thanks for valuable comment @jbathegit 
I have not introduce new descriptor in order to distinguish the difference between 3 instrument temperature.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022) notes: 

still waiting for feedback by mid-June

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja @jbathegit Comments after CGMS TFSDC review as follows:
Add new satellite sub-identifier 0-01-016 at the start of the Table D sequence.
Giving various coordinate descriptors (in sequence those from 0-05-001 to 0-05-022) for every channel and in every subset will make for a very big product. We should be really sure that all the descriptors really need to reproduced separately for every channel.

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja @jbathegit Also please change the name of the sequence not to refer to TROPICS, then we can use it for other similar data (like forthcoming AWS). If it were only for TROPICS, we wouldn't need delayed replication, etc.

Not suggestion to add satellite sub-identifier 0-01-016 will also help make the Table D sequence useful for other constellations

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM @jbathegit @amilan17 

One difficulty with re-using templates tends to be the quality flags (33094) which often are specific to instrument processing. But one could probably accommodate different processing flags for other missions. 

We can rename 0-33-094 TROPICS calibration quality flags to calibration quality flags.

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM thank you for example of groping channels

We need to have channels ids related  with location, brightness temperature and quality information.
There are 3d arrays e.g   brightness_temperature (channels, scans, spots) , latitude(channels, scans, spots), longitude(channels, scans, spots), satellite-zenith(channels, scans, spots), bearing(channels, scans, spots), 
solar-zenith(channels, scans, spots), solar-azimuth(channels, scans, spots)

where channels =12, scans=2859, spots=81, 

Also, we need to use subsets to accommodate 81 spots.

**Comment by marijanacrepulja** [comment]
> @SimonElliottEUM @jbathegit @amilan17
> 
> One difficulty with re-using templates tends to be the quality flags (33094) which often are specific to instrument processing. But one could probably accommodate different processing flags for other missions.
> 
> We can rename 0-33-094 TROPICS calibration quality flags to calibration quality flags.

@SimonElliottEUM we already have 033076 Calibration quality flags 
I believe we should come up with other name for 033094. 
Shall we name it  Calibration quality control  flags?

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja @jbathegit @amilan17 we already have 0-33-076 "Calibration quality flags". But it doesn't matter even if the same name comes twice. "Calibration quality control flags" is also fine.
Much more important is the replication for the arrays. I think there is work to be done here and the proposal is not mature enough. As TROPICS 2 & 3 have just been destroyed, and there will be a pause, we are not in a great rush. _Please could we give ourselves another 6 months and address this carefully?_

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM @jbathegit @amilan17 

The size of the BUFR file is 37MB. I believe it should not be an issue. With my RD colleagues we did consider the differences for looping over channels vs. ‘bands’, deciding that looping over channels was simpler and likely more straightforward if applied to future sensors. Despite file size, grouping over bands for geolocation could be misleading and not easy to relate to channel number, brightness temperature and quality information. Also, we would like to use data in operation and delay in approving BUFR template for TROPICS and making it operational in November 2023 would be too late.

**Comment by amilan17** [comment]
@marijanacrepulja @SimonElliottEUM @jbathegit -- 

Marijana wants this to go through fast-track 2022-2 and if all are in agreement with current discussion resolutions, then the branch needs to be updated and validated by mid-next week. Is this possible? If not, we will have to wait until FT2023-1.

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM 
I followed your approach to group the channels and have the coordinates for each group. The BUFR size is 10MB for 1.5 hours of data which is in line with other data sets. e.g FY-3D MWHS-2 data from one 6-hour file in BUFR has size of 39MB
Could you please have a look.  
If we can agree with it I will update the branch and provide sample data.
Many thanks. 

|310078| | Satellite sounding data| Note|
|--|-- |--|-----|
||1007 | SATELLITE IDENTIFIER ||
||2019 |  SATELLITE INSTRUMENTS ||
||2020 |  SATELLITE CLASSIFICATION ||
||1033 |  IDENTIFICATION OF ORIGINATING/GENERATING CENTRE ||
||1034 |  IDENTIFICATION OF ORIGINATING/GENERATING SUB-CENTRE ||
||301011 |  YEAR, MONTH, DAY ||
||301012 |  HOUR,MINUTE, SECOND |
||4007| SECONDS WITHIN A MINUTE (MICROSECOND ACCURACY)||
||5040 | ORBIT NUMBER ||
||201132| INCREASE WIDTH||
||5041 | SCAN LINE NUMBER ||
||201000| INCREASE WIDTH CANCEL||
||5043 | FIELD OF VIEW NUMBER ||
||33079 | GRANULE LEVEL QUALITY FLAGS ||
||33080 | SCAN LEVEL QUALITY FLAG ||
||33078 | GEOLOCATION QUALITY ||
||7002 |  HEIGHT OR ALTITUDE||
||102003| DELAYED DESCRIPTOR REPLICATION FACTOR |Replicating three times to accommodate 3 temperatures|
||08097| METHOD USED TO CALCULATE THE AVERAGE INSTRUMENT TEMPERATURE| |
||012164| INSTRUMENT TEMPERATURE| |
||117000 | REPLICATION OF 17 DESCRIPTORS| Replicate 18 descriptors |
||31001 | DELAYED DESCRIPTOR REPLICATION FACTOR ||
||5001 |  LATITUDE (HIGH ACCURACY) ||
||6001 |  LONGITUDE (HIGH ACCURACY) ||
||7024 |  SATELLITE ZENITH ANGLE ||
||5021 | BEARING OR AZIMUTH ||
||7025 | SOLAR ZENITH ANGLE ||
||5022 | SOLAR AZIMUTH ||
||109000| REPLICATION OF 9 DESCRIPTORS |
|| 31001| DELAYED REPLICATION FACTOR|
||5042 | CHANNEL NUMBER ||
||2153 | SATELLITE CHANNEL CENTRE FREQUENCY ||
||2154 | SATELLITE CHANNEL BAND WIDTH ||
||2104 | ANTENNA POLARISATION ||
||12066 | ANTENNA TEMPERATURE ||
||12163 | BRIGHTNESS TEMPERATURE ||
||12158 | NOISE-EQUIVALENT DELTA TEMPERATURE WHILE VIEWING COLD TARGET ||
||12159 |  NOISE-EQUIVALENT DELTA TEMPERATURE WHILE VIEWING WARM TARGET ||
||33094 | CALIBRATION QUALITY CONTROL FLAGS|| ||

**Comment by SimonElliottEUM** [comment]
I am still uncomfortable with this. I note that it was probably written in a bit of a hurry. 
"102003	DELAYED DESCRIPTOR REPLICATION FACTOR" does not refer to delayed replication and there is no replication factor in the sequence.
"117000	REPLICATION OF 17 DESCRIPTORS" is delayed replication but the wording doesn't reflect that.
Generally double nested delayed replication data are very tricky to handle in terms of memory allocation. For TROPICS (again noting no rush as satellites 2 and 3 just failed) there could equally well be fixed replication.
I am on leave until 07/07/22 for family issues in UK. I remain uncomfortable rushing this through for FT 2022-2, but in extremis I guess it could work

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM many thanks for your feedback. 

I have fixed the wording for the delayed replication. 
As for double nested delayed replication, I had a look at the existing BUFR sequences and there are few BUFR sequences using that approach. e.g. 307102, 308015. I believe users can handle that.  
I have used double nested delayed replication to make this BUFR sequence generic so can be re used for the future mission. We could have any number of groups of channels with the same geolocation, and any number of channels within that group. If I make fix replication that will work only for TROPICS. My understanding was that main idea is to create BUFR sequence to be generic. 
I don't know what additional work needs to be done, I believe we can use the sequence to encode TROPICS and other similar missions. Therefore I updated branch with new entries, also provided the sample data. I would be grateful if we can finalise validation. 

[tropics.tar.gz](https://github.com/wmo-im/BUFR4/files/9063419/tropics.tar.gz)

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM can we agree what is the plan for the TROPICS template. Would you be able to validate the samples or have any other proposals? Many thanks.

**Comment by marijanacrepulja** [comment]
@amilan17 as we discussed I have changed this issue to propose new descriptors for representation of TROPICS data. This will help using data in operation until we define BUFR template. The BUFR descriptors have been discussed at the meeting.

Could you please review the branch and move it to ready to FT.

**Comment by marijanacrepulja** [comment]
[tropics.tar.zip](https://github.com/wmo-im/BUFR4/files/10105409/tropics.tar.zip)

@SimonElliottEUM  Could you please validate the provided sample? Many thanks!

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja @amilan17 So far it looks good to me. Can you let me have the corresponding data in their original format (netCDF or HDF maybe), so that I can confirm the decoded output from BUFR matches?

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM 
Many thanks for your support with this. The size of netCDF exceeds the 25MB limit. I'll send you an email with the file.
