### ISSUE TITLE
Update note of B/C25.7.2.8 Wind direction and speed

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#130]
# Summary and purpose
ET-UAM is revising WMO No. 8 and is concerned that the old coding rules about reporting wind direction near the poles are unhelpful when it comes to radiosonde reports in BUFR with the location reported at every level. It is proposing a change to the B/C Regulations on this point (for BUFR reports, the rules for TAC would remain the same). 

# Stakeholders
* ET on Upper Air Measurements
* Pekka Rossi (Secretariat)

# Discussions
**1. Does the draft text for WMO-No. 8 conflict with the B/C Regulation?** 
* WMO-No. 8 revision: 
_Particular care is needed in reporting wind direction near to the North or South Pole. A radiosonde crossing the North Pole must be in a southerly airflow just before crossing the Pole and in a northerly airflow just afterwards. The direction should be reported according to the currently reported latitude and longitude._ 

* B/C25.7.2.8 note: 
_Note: Wind direction measured at a station within 1° of the North Pole or within 1° of the South Pole shall be reported in such a way that the azimuth ring shall be aligned with its zero coinciding with the Greenwich 0° meridian._

**2. Should the note in the B/C Regulation be updated?**
Suggested revision for note 
_Note: For alphanumeric codes wind direction measured at a station within 1° of the North Pole or within 1° of  the South Pole shall be reported in such a way that the azimuth ring shall be aligned with  its zero coinciding with the Greenwich 0° meridian. For BUFR codes the wind direction at each level should be consistent with the reported longitude at that level._

Background information
[RadiosondeIssues.docx](https://github.com/wmo-im/BUFR4/files/8947393/RadiosondeIssues.docx)

# Detailed proposal
Keeps details up to date as decisions are finalized.

**Comment by jbathegit** [comment]
Not that I'm in any way an expert on instrument reporting methods, but the reasoning here and in Bruce Ingleby's attached document seems sensible, so I would support this proposed update.

The only question I have is the use of "should" vs "shall" in the last sentence of the wording for the proposed update.  Is there any reason not to use "shall", in order to make this a mandatory practice?

**Comment by amilan17** [comment]
I think they should both be 'should', given that it's a note and notes don't have regulatory status.

**Comment by jbathegit** [comment]
Fair enough, but just to clarify, are you proposing that the two occurrences of "shall" in the first sentence of the proposed update should be changed to "should" as well?

**Comment by SimonElliottEUM** [comment]
@amilan17 @jbathegit I have also had a chance to read Bruce Ingleby's document and, like Jeff, find it eminently sensible. I support the proposed change to the note in the B/C Regulation

**Comment by amilan17** [comment]
We don't want to reference anything related to alphanumeric codes, because they are deprecated.

**Comment by amilan17** [comment]
closing, because it's past INFCOM-2.
