### ISSUE TITLE
New BUFR template for TROPICS

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#132]
# Summary and purpose

ECMWF is proposing new BUFR template for representing TROPICS observations.

# Stakeholders

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for operational assimilation of TROPICS observations. Therefore, we need a new BUFR template and entry for calibration quality flags to accommodate observation from TROPICS.

# Detailed proposal

**1. Add a new BUFR template for TROPICS**

|310078| | Satellite sounding data| Note|
|--|-- |--|-----|
||001007 | SATELLITE IDENTIFIER ||
|| 001016 |  SATELLITE SUB IDENTIFIER|
||002019 |  SATELLITE INSTRUMENTS ||
||002020 |  SATELLITE CLASSIFICATION ||
||001033 |  IDENTIFICATION OF ORIGINATING/GENERATING CENTRE ||
||001034 |  IDENTIFICATION OF ORIGINATING/GENERATING SUB-CENTRE ||
||301011 |  YEAR, MONTH, DAY ||
||301013 |  HOUR,MINUTE, SECOND |
||005040 | ORBIT NUMBER ||
||201132| CHANGE DATA WIDTH|
||005041 | SCAN LINE NUMBER ||
||201000| CHANGE DATA WIDTH| CANCEL |
||005043 | FIELD OF VIEW NUMBER ||
||033079 | GRANULE LEVEL QUALITY FLAGS ||
||033080 | SCAN LEVEL QUALITY FLAG ||
||033078 | GEOLOCATION QUALITY ||
||007002 |  HEIGHT OR ALTITUDE||
||102003|  REPLICATE 2 DESCRIPTORS 3 TIMES  ||
||008097| METHOD USED TO CALCULATE THE AVERAGE INSTRUMENT TEMPERATURE| |
||012164| INSTRUMENT TEMPERATURE| |
||117000 |  DELAYED REPLICATION OF 17 DESCRIPTORS|  |
||031001 | DELAYED DESCRIPTOR REPLICATION FACTOR ||
||005001 |  LATITUDE (HIGH ACCURACY) ||
||006001 |  LONGITUDE (HIGH ACCURACY) ||
||007024 |  SATELLITE ZENITH ANGLE ||
||005021 | BEARING OR AZIMUTH ||
||007025 | SOLAR ZENITH ANGLE ||
||005022 | SOLAR AZIMUTH ||
||109000| DELAYED REPLICATION OF 9 DESCRIPTORS |
|| 31001| DELAYED REPLICATION FACTOR|
||005042 | CHANNEL NUMBER ||
||002153 | SATELLITE CHANNEL CENTRE FREQUENCY ||
||002154 | SATELLITE CHANNEL BAND WIDTH ||
||002104 | ANTENNA POLARISATION ||
||012066 | ANTENNA TEMPERATURE ||
||012163 | BRIGHTNESS TEMPERATURE ||
||012158 | NOISE-EQUIVALENT DELTA TEMPERATURE WHILE VIEWING COLD TARGET ||
||012159 |  NOISE-EQUIVALENT DELTA TEMPERATURE WHILE VIEWING WARM TARGET ||
||033094 | CALIBRATION QUALITY CONTROL FLAGS|| ||

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-22.9.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-22.9.2022) notes:

*   change 301013 to 301012, because don't need to have seconds repeated
*   change to fixed replication instead of delayed and keep the template specific to TROPICS

**Comment by marijanacrepulja** [comment]
According to a my research colleague's comment, ||004007| SECONDS WITHIN A MINUTE (MICROSECOND ACCURACY)|| is not required in the BUFR template. I have remove it and kept 301013.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-21.11.2022 notes: 
EUMETSAT will validate, @marijanacrepulja will update branch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes:

Simon validated the data and would still like to see the NetCDF to verify.

**Comment by marijanacrepulja** [comment]
I have uploaded a sample netCDF file TROPICS.nc on SharePoint

**Comment by amilan17** [comment]
I think this URL will take you to the file: [TROPICS.nc](https://wmoomm.sharepoint.com/:u:/r/sites/wmocpdb/eve_group/Task%20Team%20on%20Table%20Driven%20Code%20Forms%20(TT-TDCF)_29c30824-8aee-ea11-a817-000d3aafe55d/Group%20Members/documents/TROPICS.nc?csf=1&web=1&e=W1HXHp)

**Comment by amilan17** [comment]
@marijanacrepulja -- I checked the branch for consistency. It looks good, but there is one minor difference between the proposal and the branch. 

<table><tbody><tr><td>201000</td><td>INCREASE WIDTH CANCEL</td></tr></tbody></table>

vs

<table><tbody><tr><td>201000</td><td>Increase width by 4 bits</td><td>Cancel</td></tr></tbody></table>

**Comment by SimonElliottEUM** [comment]
> @SimonElliottEUM I think this URL will take you to the file: [TROPICS.nc](https://wmoomm.sharepoint.com/:u:/r/sites/wmocpdb/eve_group/Task%20Team%20on%20Table%20Driven%20Code%20Forms%20(TT-TDCF)_29c30824-8aee-ea11-a817-000d3aafe55d/Group%20Members/documents/TROPICS.nc?csf=1&web=1&e=W1HXHp)

It tells me: "Access Denied You don't have permissions to access this resource."

**Comment by marijanacrepulja** [comment]
> @marijanacrepulja -- I checked the branch for consistency. It looks good, but there is one minor difference between the proposal and the branch. 
> 
> 201000	INCREASE WIDTH CANCEL
> vs
> 
> 201000	Increase width by 4 bits	Cancel

@amilan17 Thank you for spotting it. I have updated branch and proposal to be consistent with wording used in other BUFR templates.

**Comment by SimonElliottEUM** [comment]
> 

That worked just fine. Thanks.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes:

@amilan17 ready for final review
