### ISSUE TITLE
New BUFR template for Aerosol Optical Depth 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#138]
### Initial request

ECMWF is proposing new BUFR template for representing AOD observations.

### Amendment details

**1. Add a new element  in table B 0-07-073 Scattering angle**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-07-073 |Scattering angle| deg | 0 | 0 | 8

**2. Add a new element  in table B 0-07-074 Relative azimuth angle**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-07-074 |  Relative azimuth angle| deg | 0 | 0 | 8

**3. Add a new element  in table B 0-08-098 Sensing direction ** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-08-098 |SensingDirection| CODE TABLE | 0 | 0 | 4

**4. Add a new CODE/FLAG TABLE 0-08-098 for Sensing direction**
|Code| Sensing direction| 
|----|-----| 
|0| Nadir|
|1| Oblique|
|2-14| Reserved
|15| Missing value

**5. Add a new element  in table B 0-33-095 Aerosol optical depth quality information**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-33-095 |   Aerosol Optical Depth Quality Information| CODE TABLE | 0 | 0 | 5

**6. Add a new CODE/FLAG TABLE 0-33-095 for Aerosol optical depth quality information**
|Code|  Aerosol optical depth quality information |  
|----|-----| 
|0| Good|
|1| Cloudy nadir|
|2| Cloudy oblique |
|3| Glint nadir |
|4| Glint oblique |
|5-30| Reserved
|31| Missing value

**7. Add a new BUFR template for AOD**

|322001| | Aerosol Optical Depth| Note|
|--|--|--|-----|
||310022 | Satellite identifier, instrument  and product type ||
||301011 | Year, month, day||
||301013 | Hour, minute, second||
||301021 |  Latitude/longitude (high accuracy)|
||005041 | Scan line number ||
||005043 | Field of view number ||
||027080 | Viewing azimuth angle||
||005022 |  Solar azimuth||
||013040 |  Surface flag ||
||020010| Cloud cover (total)|
||033085 | Aerosol optical thickness quality flags||
||033095 | Aerosol optical depth quality information||
||105002| Replicate 5 descriptors 2 times ||
||008098| Sensing direction||
||007024 | Satellite zenith angle||
||007025 | Solar zenith angle||
||007073 | Scattering angle ||
||007074 | Relative azimuth angle||
||106000 | Delayed replication of 6 descriptors   ||
||031001 | Delayed replication factor    ||
||002071 | Spectrographic wavelength||
||008043| Atmospheric chemical or physical constituent type|
||015024| Optical depth||
||008043| Atmospheric chemical or physical constituent type||
||015024| Optical depth||
||015042|  Reflectance ||
||224000| First-order statistical values follow||
||236000| Define data present bit-map||
||101000| Delayed replication of 1 descriptors||
||031002| Extended delayed descriptor replication factor|
||031031| Data present indicator||
||001033| Identification of originating/ generating centre||
||001032| Generating application||
||008023| First-order statistics||
||101000 | Delayed replication of 1 descriptors   ||
||031002 |Extended delayed descriptor replication factor||
||224255| First-order statistical values marker operator ||

### Comments

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

### Requestor(s)

Roberto Ribas, Marijana Crepulja, Angela Benedetti, Mel, Sebastien (all from ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR code table 0 20 009

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022) notes:

team discussed some issues that @marijanacrepulja will fix.

**Comment by sergioh-pessoal** [comment]
Hello @marijanacrepulja 

    I decoded the sample with mbufrtools and checked the values. Values are the same. So it seems valid.

   On the other hand, the current version of my software has a limitation. It is not prepared to process the marker operator 2-24-255.

So I was able to verify only if the decoded values are OK, but the part related to the association through the bitmap with firstOrderStatisticalValue I could not verify.


Attached is the decoded text file.
[aod.decoded.txt.gz](https://github.com/wmo-im/BUFR4/files/10204252/aod.decoded.txt.gz)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes:

@marijanacrepulja will update branch for **CODE/FLAG TABLE 0-08-098** should be up to 15 only and edit the 105002 description needs to be updated.

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated the branch to be align with the proposal. Could you please confirm and move it to "Ready for FT Approval procedure"
Many thanks!

**Comment by amilan17** [comment]
@marijanacrepulja I completed the consistency check and it looks good except for the bulleted items below. 

1.  Inconsistency across Code table 33, Table B 33 and Table D 22

<table><tbody><tr><td>033095</td><td>Aerosol optical depth quality information</td></tr></tbody></table>

vs

<table><tbody><tr><td>033095</td><td>Aerosol optical depth quality flags</td></tr></tbody></table>

2\. I think you deleted a couple lines from METOP GOME-2 in Table D 22 (see [https://github.com/wmo-im/BUFR4/compare/master...138-new-bufr-template-for-aerosol-optical-depth#diff-c4040af37cc4822644bd36e4ba979d7f4dd18c409d41b0fac2636e399d2fcbaa)](https://github.com/wmo-im/BUFR4/compare/master...138-new-bufr-template-for-aerosol-optical-depth#diff-c4040af37cc4822644bd36e4ba979d7f4dd18c409d41b0fac2636e399d2fcbaa))

3\. Did you mean to repeat these sequences in Table D 22? 

<table><tbody><tr><td>008043</td><td>Atmospheric chemical or physical constituent type</td></tr><tr><td>015024</td><td>Optical depth</td></tr><tr><td>008043</td><td>Atmospheric chemical or physical constituent type</td></tr><tr><td>015024</td><td>Optical depth</td></tr></tbody></table>

**Comment by marijanacrepulja** [comment]
@amilan17 Thank you very much for reviewing the branch. I corrected bullets 1 and 2. Bulletin 3 is intended to be this way.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT
