### ISSUE TITLE
Proposal for new BUFR table entries for FY-4 GIIRS

### ISSUE THREAD

**Issue by shirley-xuelei** [wmo-im/BUFR4#139]
### Initial request

This document proposes new BUFR entries for FY-4 Geostationary Interferometric Infrared Sounder (GIIRS)  product.

### New table D entries
|Table references|Element name                                         |
|----------------|-----------------------------------------------------|
|3 10 191        |FY-4 Geostationary Interferometric Infrared Sounder (GIIRS)  |
### FY-4 GIIRS
Add the following sequence to BUFR TABLE D :
Add the sequence `3 10 191 "FY-4 Geostationary Interferometric Infrared Sounder (GIIRS)" :
|Table references|Element name                                         |
|----------------|-----------------------------------------------------|
|0 01 007        |Satellite identifier                                 |
|0 01 033        |Identification of originating/generating centre      |
|0 01 034        |Identification of originating/generating sub-centre  |
|0 02 019        |Satellite instruments                                |
|0 02 020        |Satellite classification                             |
|3 01 011        |(Year, month, day)                                   |
|3 01 012        |(Hour, minute)                                       |
|2 07 003        |Increase scale, reference value and data width (+3)  |
|0 04 006        |Second                                               |
|2 07 000        |Cancel increase scale, reference value and data width|
|0 07 024        |Satellite zenith angle                               |
|0 05 021        |Bearing or azimuth                                   |
|0 07 025        |Solar zenith angle                                   |
|0 05 022        |Solar azimuth                                        |
|1 02 002        |Replicate 2 descriptors 2 times                      |
|0 08 076        |Type of band                                         |
|3 01 021        |(Latitude/longitude (high accuracy))                 |
|2 01 131        |Add +3 to descriptor width                           |
|0 05 041        |Scan line number                                     |
|2 01 000        |Cancel change of width                               |
|0 05 045        |Field of regard number                               |
|2 01 133        |Add +5 to descriptor width                                 |
|0 05 043        |Field of view number                            |
|2 01 000        |Cancel change of width                               |
|2 02 126        |Add -2 to descriptor scale                                 |
|2 01 132        |Add +4 to descriptor width                                 |
|0 07 001        |Height Of Station                            |
|2 01 000        |Cancel change of scale                               |
|2 02 000        |Cancel change of width                               |
|0 25 182        |L1 processing flag                                   |
|0 02 165        |Radiance type flags                                   |
|1 08 002        |Replicate 8 descriptors 2 times　                     |
|0 08 076        |Type of band                                         |
|0 06 029        |Wave number (start of range)                         |
|0 06 029        |Wave number (end of range)                           |
|0 25 140        |Start channel                                        |
|0 25 141        |End channel                                          |
|0 33 076        |Calibration quality flags                            |
|0 33 077        |Field-of-view quality flags                          |
|0 25 187        |Confidence flag                                      |
|0 08 076        |Type of band（Set to missing)                         |
|1 05 000        |Delayed replication of 5 descriptors　                |
|0 31 002        |Extended delayed descriptor replication factor       |
|2 01 133        |Add +5 to descriptor width                           |
|0 05 042        |Channel number                                       |
|2 01 000        |Cancel change of width                               |
|0 14 044        |Channel radiance                                     |
|0 14 049        |Noise Equivalent delta Radiance              |

### Requestor(s)

EUMETSAT:
Simon Elliott

### Stakeholder(s)

XUE Lei (CMA), LI Lu (CMA), Chris Burrows (ECMWF), Nigel Atkinson (UKMO), Marijana Crepulja(ECMWF), Simon Elliott(EUMETSAT)

### Publication(s)

New entries in : Table D

### Expected impact of change

MEDIUM

### Collaborators

ECMWF scientists
EUMETSAT scientists

**Comment by shirley-xuelei** [comment]
> https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022 notes:
> 
> * @shirley-xuelei presented the proposal.
> * @marijanacrepulja: my colleagues had some comments. The four descriptors (for zenith, azimuth, etc) should repeat for each band. (LeeLu) Not needed, because they are the same for each band.
> * (@marijanacrepulja) you should probably increase the size of "Field of view number" (?), will double check. They also wanted radiance type flags. Add 0 02 156? (@SimonElliottEUM ) this is level 1 data and this flag may not be available. (Li Lu) The clear sky information is available from the imager, but ...? (@SimonElliottEUM) a compromise may be to add the desciptor, but leave it empty in case this information can be found at a later time (Li Lu) good suggestion, but it's not going to happen this year. It's ok to have the descriptor added for future use.
> * @marijanacrepulja: can you add the height information? (@shirley-xuelei) don't have this or don't know what it means (@SimonElliottEUM ) this doesn't have much meaning for geostationary data.
> * @marijanacrepulja: can you add new descriptor from issue [Table B 14: New BUFR descriptor for the GIIRS observations #85](https://github.com/wmo-im/BUFR4/issues/85)? (@SimonElliottEUM) in the HDF, there are two variables for FY4A that may be similar. (Li Lu / @shirley-xuelei) won't have this information for FY4B, but will check again after meeting. What are the benefits of adding this? (@marijanacrepulja ) not sure the main reason will ask. (@shirley-xuelei and Li Lu will discuss)
> * @SimonElliottEUM: this is complicated proposal. how often does the extended delayed replication factor change? It would be better to have fixed replication if the number of channels are constant. (@shirley-xuelei / Li Lu) The number of channels don't change.
> * @shirley-xuelei  and Li Lu will discuss, @marijanacrepulja will facilitate a small working group (if needed) to adjudicate remaining questions.

According to the comments of last meeting, I updated 4 items as follows, @marijanacrepulja @SimonElliottEUM @amilan17
1. Add 0 07 001 Height of the Station
2. Add 0 02 165 Radiance type flags, but it will be filled with the fixed value of 5(=unapodised) at present.
3. Add 0 14 049 Noise Equivalent delta Radiance (NEdR)
4. Add +5 to the width of 0 05 043 (FOV)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-21.11.2022 notes: 
(@shirley-xuelei) updated proposal

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes:

branch is updated and colleagues are working on sample data

**Comment by amilan17** [comment]
@shirley-xuelei I checked the branch for consistency and I only needed to make a couple very minor editorial changes. It looks good.

**Comment by shirley-xuelei** [comment]
> @shirley-xuelei I checked the branch for consistency and I only needed to make a couple very minor editorial changes. It looks good.

@amilan17 thank you for check and change it for me.

**Comment by amilan17** [comment]
@shirley-xuelei 
Can you upload the sample data to the Documents folder of this SharePoint directory? 

https://wmoomm.sharepoint.com/:f:/s/wmocpdb/EnqK9Y2bfGxPnXNM_yrOq5gBJrfprspEPKpXr7YVIivSbQ?e=lvTWvU

**Comment by SibylleK** [comment]
@shirley-xuelei provided some sample data

I uploaded the sample data and the DWD output to the documents folder of the SharePoint directory.
The link in @amilan17  E-Mail from 12th December 22 works.
[documents](https://ofcsg2dvf1.dwd.de/fmlurlsvc/?fewReq=:B:JVMxOj45MS19NjklOy1ibzY7OjE7Oi14Ymxlan9+eW42Ozo9OGhvPWg/aDxuPW45OTo/OGhvODltOW0+Mz9uMj84aDtqOTwybi1/Njo9PDszPj0zPj4temJvNjlJSE54TWliOzk5Mz85JjlJSE54TWlhOzk5Mz85LXloe382WGJpcmdnbiVAeW5paW55S298byVvbi1oNj45LWNvZzY7&url=https%3a%2f%2fwmoomm.sharepoint.com%2f%3af%3a%2fs%2fwmocpdb%2fEi8PI-GnmAdKoh9DThbLJc0BJp_E_4MZE8-SNynQ6h-VHA%3fe%3d4blfwS)

The output of the BUFR samples looks good to me.
@shirley-xuelei could you check or provide your output for comparison?

**Comment by SimonElliottEUM** [comment]
@shirley-xuelei @SibylleK @amilan17 I have been able to access the BUFR sample data via the documents folder in the sharepoint directory. My first checks suggest that the data does not have the BUFR compression enabled - of course we can still do the validation without that, but it is unusual to see satellite data without the compression. Perhaps @shirley-xuelei can provide an additional sample with compression enabled in the BUFR - for completeness.

**Comment by marijanacrepulja** [comment]
@amilan17 I was not able to upload output of ECMWF decoding software, so I am attaching it here. 

[FY4B-_GIIRS-_N_REGC_1330E_L1-_IRD-_MULT_NUL_20220920154828_20220920155336_012KM_010V1-rev.bfr.ECMWFout.zip](https://github.com/wmo-im/BUFR4/files/10447786/FY4B-_GIIRS-_N_REGC_1330E_L1-_IRD-_MULT_NUL_20220920154828_20220920155336_012KM_010V1-rev.bfr.ECMWFout.zip)

I did cross-check values from the DWD output provided by @SibylleK. The decoding values are the same. 

@shirley-xuelei  thank you for proving the samples. 
@SimonElliottEUM  thank you for pointing out about the compression. 

I believe we can finalise validation.

**Comment by amilan17** [comment]
@shirley-xuelei @SibylleK @marijanacrepulja 

Is there a reason why the sequence number starts is "3 10 **191**" instead of "3 10 **078**"? Does it matter?

**Comment by shirley-xuelei** [comment]
> @shirley-xuelei @SibylleK @marijanacrepulja 
> 
> Is there a reason why the sequence number is "3 10 **191**" instead of ~"3 10 **078**"~  "3 10 **079**"? Is it because of the conflict with the sequence number in issue #132  and does it matter?

@amilan17 @SibylleK @marijanacrepulja I choose '3 10 191' at first just beacause I followed the issue #136，and I remember issue #136 used '3 10 19*' at that time.  '3 10 079' is ok for me, it doesn't matter. Shall I update the sequence to '3 10 079' ?  And is it necessary to redo the sample data with the new descriptor?

**Comment by amilan17** [comment]
@shirley-xuelei thank you for the information. I don't think it's necessary to update anything or revalidate at this point.
