### ISSUE TITLE
register BUFR MIME type with IANA

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/BUFR4#140]
### Details

As discussed at WMO WIS2 meetings earlier this week, various implementations have used `application/x-bufr` as a media type when providing BUFR4 responses via APIs. For interoperability and consistency, a media type for BUFR (`application/bufr`) should be officially registered with IANA.

Note that the OGC may be able to help with this process.

cc @6a6d74 @chris-little @solson-nws 

### Requestor

Tom Kralidis (MSC), @tomkralidis

**Comment by chris-little** [comment]
@tomkralidis Agreed, we should be registering `application/bufr` with IANA, and not `bufr4` etc.

**Comment by tomkralidis** [comment]
Update: registration process with IANA can be found at https://www.iana.org/form/media-types

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023 notes:

The team discussed options with GRIB use cases and noted that IANA MIME types are outside their area of expertise.
see for more details https://github.com/wmo-im/GRIB2/issues/175

**Comment by chris-little** [comment]
@amilan17 I have assumed that the same apporach will be used for both GRIB and BUFR.. Is everyone agreed on that?

**Comment by amilan17** [comment]
https://www.iana.org/assignments/media-types/media-types.xhtml#application

**Comment by manfredsc** [comment]
Request for the unix "file" (https://www.darwinsys.com/file/) database:
https://bugs.astron.com/view.php?id=540
