### ISSUE TITLE
Proposal for new BUFR table entries for Sentinel-6 Michael Freilich

### ISSUE THREAD

**Issue by erget** [wmo-im/BUFR4#15]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue-15

# Summary and purpose
This document proposes new BUFR entries in order to represent altimeter data from Sentinel-6 Michael Freilich.

# Action proposed
The meeting is requested to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
Sentinel-6 Michael Freilich is due to be launched in the autumn of 2020. In order to ensure the standardized exchange of data from the radiometer mission, a number of BUFR table entries have been developed and are proposed here for adoption.

# Detailed proposal
Add the following sequence 3-40-019 “Altimeter product” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 3-40-020 | Satellite general values |
| 3-40-021 | General radiometer values |
| 3-40-022 | Altimeter model values |
| 3-40-023 | Altimeter main values |

Add the following sequence 3-40-020 “Satellite general values” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 0-01-007 | Satellite   identifier |
| 0-02-019 | Satellite   instruments |
| 0-05-044 | Satellite   cycle number |
| 0-01-096 | Station   acquisition |
| 0-05-040 | Orbit   number |
| 0-01-040 | Processing   centre id code |
| 0-25-061 | Software   identification and version number |
| 0-25-182 | L1 processing   flag |
| 0-25-183 | L1   processing quality |
| 0-25-181 | L2   processing flag |
| 0-25-184 | L2   product status |
| 0-08-075 | Ascending/descending   orbit qualifier |
| 0-25-090 | Orbit   state flag |
| 3-01-011 | Date |
| 3-01-013 | Time |
| 0-04-007 | Seconds   within a minute (microsecond accuracy) |
| 3-01-021 | Latitude   and longitude (high resolution) |
| 0-05-063 | Spacecraft   roll |
| 0-05-064 | Spacecraft   pitch |
| 0-05-066 | Spacecraft   yaw |
| 0-10-081 | Altitude   of cog above reference ellipsoid |
| 0-10-082 | Instantaneous   altitude rate |

Add the following sequence 3-40-021 “General radiometer values” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 0-40-012 | Radiometer   data quality flag |
| 0-08-077 | Radiometer   sensed surface type |
| 1-04-000 | Delayed replication |
| 0-31-001 | Delayed descriptor replication factor
| 0-02-153 | Satellite   channel centre frequency |
| 0-12-063 | Brightness   temperature |
| 0-12-065 | Standard   deviation brightness temperature |
| 0-40-013 | Radiometer   brightness temperature interpretation flag |
| 0-07-002 | Height   or altitude |
| 0-11-098 | Wind   speed from radiometer |

Add the following sequence 3-40-022 “Altimeter model values” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 0-08-029 | Surface   type |
| 2-01-137 | Change   data width |
| 2-02-129 | Change   data scale |
| 0-06-021 | Distance |
| 2-02-000 | Reset   scale |
| 2-01-000 | Reset   width |
| 0-10-087 | Ocean   depth/land elevation |
| 0-40-024 | Meteorological   map availability |
| 0-07-002 | Height   or altitude |
| 0-25-126 | Model   dry tropospheric correction |
| 0-25-128 | Model   wet tropospheric correction |
| 0-40-011 | Interpolation   flag |
| 0-07-002 | Height   or altitude |
| 0-11-095 | U-component   of the model wind vector |
| 0-11-096 | V-component   of the model wind vector |
| 0-10-088 | Total   geocentric ocean tide height (solution 1) |
| 0-10-089 | Total   geocentric ocean tide height (solution 2) |
| 0-10-090 | Long   period tide height |
| 0-10-092 | Solid   earth tide height |
| 0-10-093 | Geocentric   pole tide height |
| 0-10-098 | Loading   tide height geocentric ocean tide solution 1 |
| 0-10-099 | Loading   tide height geocentric ocean tide solution 2 |
| 0-10-100 | Non-equilibrium   long period tide height |
| 0-25-127 | Inverted   barometer correction |
| 0-40-014 | High-frequency   fluctuations of the sea-surface topography correc |
| 0-01-030 | Numerical   model identifier |
| 0-10-085 | Mean   sea-surface height |
| 0-01-030 | Numerical   model identifier |
| 0-10-085 | Mean   sea-surface height |
| 0-10-086 | Geoid's   height |
| 0-10-096 | Mean   dynamic topography |
| 0-10-103 | Mean   dynamic topography accuracy |
| 0-21-169 | Ice   presence indicator |
| 0-13-055 | Intensity   of precipitation |
| 0-25-165 | Ionospheric   correction from model on specific band | 

Add the following sequence 3-40-023 “Altimeter main values” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 0-25-095 | Altimeter   state flag |
| 0-40-023 | Auxiliary   altimeter state flags |
| 0-08-074 | Altimeter   echo type |
| 3-40-024 | 1 Hz C and Ku band values |
| 3-40-024 | 1 Hz C and Ku band values |
| 3-40-024 | 1 Hz C and Ku band values |
| 3-40-025 | 20 Hz C and Ku band values |

Add the following sequence 3-40-024 “1 Hz C and Ku band values” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 0-22-080 | Waveband   central frequency |
| 0-08-076 | Type   of band |
| 0-25-190 | Altimeter   echo processing mode |
| 0-10-102 | Sea-surface   height anomaly |
| 0-22-189 | Specific   band ocean range |
| 0-22-191 | Rms   of specific band ocean range |
| 0-22-130 | Number   of valid points for specific band |
| 0-25-167 | Specific   band net instrumental correction |
| 0-25-163 | Altimeter   ionospheric correction on ku band |
| 0-15-012 | Total   electron count per square metre |
| 0-25-164 | Radiometer   wet tropospheric correction |
| 0-13-090 | Radiometer   water vapour content |
|  0-13-091 | Radiometer   liquid content |
| 0-25-166 | Sea   state bias correction on specific band |
| 0-07-002 | Height   or altitude |
| 0-11-097 | Wind   speed from altimeter |
| 0-21-183 | Specific   band corrected ocean backscatter coefficient |
| 0-21-184 | Std   specific band corrected ocean backscatter coefficient |
| 0-22-134 | Number   of valid points for specific band backscatter |
| 0-21-122 | Attenuation   correction on sigma-0 (from tb) |
| 0-21-186 | Specific   band automatic gain control |
| 0-21-187 | Rms   specific band automatic gain control |
| 0-21-188 | Number   of valid points for specific band automatic gain control |
| 2-01-131 | Change   data width |
| 0-21-185 | Specific   band net instrumental correction for agc |
| 2-01-000 | Reset   width |
| 0-22-179| Specific   band significant wave height |
| 0-22-131 | Rms   specific band significant wave height |
| 0-22-132 | Number   of valid points for specific band significant wave height |
| 0-22-133 | Specific   band net instrument correction for significant wave height |
| 0-21-144 | Altimeter   rain flag |
| 0-25-191 | Altimeter   tracking mode |
| 0-21-143 | Ku   band rain attenuation |
| 0-10-101 | Squared   off-nadir angle of the satellite from waveform data |
| 0-25-112 | Band   specific altimeter data quality flag |
| 0-25-113 | Band   specific altimeter correction quality flag |
| 0-33-092 | Band   specific ocean quality flag |       

Add the following sequence 3-40-025 “20 Hz C and Ku band values” to BUFR Table D/01:

| Table references | Element name |
| --- | --- |
| 0-08-049 | Number   of observations |
| 0-22-080 | Waveband   central frequency |
| 0-08-076 | Type   of band |
| 0-25-190 | Altimeter   echo processing mode |
| 1-46-021 | Replication |
| 3-01-011 | Date |
| 3-01-013 | Time |
| 0-04-007 | Seconds   within a minute (microsecond accuracy) |
| 3-01-021 | Latitude   and longitude (high resolution) |
| 0-10-081 | Altitude   of cog above reference ellipsoid |
| 0-10-082 | Instantaneous   altitude rate |
| 0-08-029 | Surface   type |
| 2-01-137 | Change   data width |
| 2-02-129 | Change   data scale |
| 0-06-021 | Distance |
| 2-02-000 | Reset   scale |
| 2-01-000 | Reset   width |
| 0-25-191 | Altimeter   tracking mode |
| 0-21-071 | Peakiness |
| 0-01-030 | Numerical   model identifier |
| 0-10-085 | Mean   sea-surface height |
| 0-01-030 | Numerical   model identifier |
| 0-10-085 | Mean   sea-surface height |
| 0-40-011 | Interpolation   flag |
| 0-10-088 | Total   geocentric ocean tide height (solution 1) |
| 0-10-089 | Total   geocentric ocean tide height (solution 2) |
| 0-25-164 | Radiometer   wet tropospheric correction |
| 0-07-002 | Height   or altitude |
| 0-25-126 | Model   dry tropospheric correction |
| 0-25-128 | Model   wet tropospheric correction |
| 0-10-102 | Sea-surface   height anomaly |
| 0-22-189 | Specific   band ocean range |
| 0-25-167 | Specific   band net instrumental correction |
| 0-25-163 | Altimeter   ionospheric correction on ku band |
| 0-21-183 | Specific   band corrected ocean backscatter coefficient |
| 2-01-131 | Change   data width |
| 0-21-185 | Specific   band net instrumental correction for agc |
| 2-01-000 | Reset   width |
| 0-22-179 | Specific   band significant wave height |
| 0-22-133 | Specific   band net instrument correction for significant wave height |
| 0-22-146 | Ocog   range |
| 0-21-189 | Corrected   OCOG* backscatter coefficient |
| 0-13-163 | Snow   water equivalent |
| 2-02-126 | Change   data scale |
| 0-22-046 | Sea   ice fraction |
| 2-02-000 | Reset   scale |
| 0-13-117 | Snow   density (liquid water content) |
| 0-13-013 | Total   snow depth |
| 0-25-112 | Band   specific altimeter data quality flag |
| 0-25-113 | Band   specific altimeter correction quality flag |
| 0-33-092 | Band   specific ocean quality flag |             

Add the following elements to BUFR Table B/40:

| Descriptor | Name | Units | Scale | Reference | Width |
| --- | --- | --- | --- | --- | --- |
| 0-21-189 | Corrected OCOG* backscatter coefficient (negative reference) | dB | 2 | -32768 | 16 |
| 0-22-179 | Specific band significant wave height  (negative reference) | M | 3 | -500 | 16 |      

Notes:
- 0-21-189 is similar to 0-21-177, but with a negative reference value
- 0-22-179 is similar to 0-22-190, but with a negative reference value

**Comment by jbathegit** [comment]
Hi Daniel - a reminder that Y > 191 means a descriptor is local, so your proposed new FXY numbers 0-21-192, 0-22-192 and 3-40-192, 3-40-193, ..., 3-40-198 all need to be adjusted to put them into the WMO standard range where Y <= 191.

**Comment by erget** [comment]
Hi Jeff, yes, you're right - the thought here was that there might be number clashes so we'd discuss the sequences and then when they're ok have the Secretariat assign the final numbers.

**Comment by SimonElliottEUM** [comment]
It was a cunning plan on my part. It doesn't matter which numbers we get - I though it might be helpful to have them assigned by the Secretariat

**Comment by marijanacrepulja** [comment]
Hi Daniel, 
Many thanks for BUFR templates. 

-   Could we not include satellite name in the name of the BUFR template since the same template will be used for other altimeters.

- Would't it better if the following elements are moved from the "3-40-197 “Sentinel-6 Michael Freilich 1 Hz C and Ku band values" part to the "3-40-194 “Sentinel-6 Michael Freilich radiometer values" part:
0-25-164 Radiometer wet tropospheric correction
0-13-090 Radiometer water vapour content
0-13-091 Radiometer liquid content

- In 3-40-195 why do we have twice  
0-01-030  Numerical   model identifier
0-10-085  Mean   sea-surface height

- In 3-40-194, could we use delayed replication. That is in case that we can re use it in the future.

- If element "0-21-122 Attenuation correction on sigma-0 (from tb)" is new, can we change sigma-0 to backscatter coefficient to be consistent with the other elements like: "0-21-183 Specific band corrected ocean backscatter coefficient"

**Comment by erget** [comment]
Hi @marijanacrepulja , I've answered your questions point-by-point below:

> Could we not include satellite name in the name of the BUFR template since the same template will be used for other altimeters. 

This is fine, **I have updated the sequence names accordingly.**

> Would't it better if the following elements are moved from the "3-40-197 “Sentinel-6 Michael Freilich 1 Hz C and Ku band values" part to the "3-40-194 “Sentinel-6 Michael Freilich radiometer values"...

Those descriptors are proposed for 3-40-197 because the retrieved values use the radiometer brightness temperatures _and_ the altimeter's Sigma0, so they should remain in that sequence.

> ...why do we have twice 0-01-030 ... 0-10-085

The product will contain 2 MSS models in the product, this is to allow describing both of them.

> In 3-40-194, could we use delayed replication

Yes, **I have updated the sequence accordingly.**

> If element "0-21-122 Attenuation correction on sigma-0 (from tb)" is new, can we change sigma-0 to backscatter coefficient to be consistent with the other elements like: "0-21-183 Specific band corrected ocean backscatter coefficient"

0-21-122 already exists, we would prefer  to reuse it.

**Comment by chenxiaoxia2019** [comment]
@erget Hi, Daniel, I changed the FXY number of Corrected OCOG* backscatter coefficient (negative reference) from 0-21-192 to 0-21-189 and changed the FXY number of Specific band significant wave height (negative reference) from 0-22-192 to 0-22-179. And, I also changed from 340192 to 340018, 340193 to 340019, 340194 to 340020, 340195 to 340021, 340196 to 340022, 340197 to 340023, 340198 to 340024. More information about the CREX_Unit, CREX_Scale, CREX_DataWidth_Char, Status are needed. A branch for this issue is created. Please check it. Many thanks.

**Comment by erget** [comment]
@chenxiaoxia2019 I note the following changes:
- 0-21-192 to 0-21-189
- 0-22-192 to 0-22-179
- 3-40-192 to 3-40-018
- 3-40-193 to 3-40-019
- 3-40-194 to 3-40-020
- 3-40-195 to 3-40-021
- 3-40-196 to 3-40-022
- 3-40-197 to 3-40-023
- 3-40-198 to 3-40-024

and have updated the proposal accordingly.

I'm a bit confused about the CREX information - this is satellite data and thus we don't intend to disseminate it in CREX. What do you require exactly?

**Comment by erget** [comment]
@chenxiaoxia2019 I have reviewed the proposed changes in the associated PR. I didn't review every file but rather `BUFR_TableD_en_40.csv` and `txt/BUFRCREX_TableB_en.txt` but of course the changes in those files will need to extend to the other ones as well.

**Comment by erget** [comment]
@chenxiaoxia2019 I note also that there is a number clash in these tables - #10 already uses 3-40-018. I propose giving the IKFS-2 sequence described in that issue to use 3-40-023 but I leave it to you to make the final decision that will not produce a number clash.

For now, I'm producing sample data as described in this proposal, i.e. #10 and #15 are both using different definitions for 3-40-018.

**Comment by erget** [comment]
I've uploaded [sample data](https://github.com/wmo-im/BUFR4/files/4799192/S6.zip) - `*.nc` is the native file, `*.bin` is the same translated into BUFR.

**Comment by marijanacrepulja** [comment]
@chenxiaoxia2019 
BUFR_TableD_en_40.csv still contains entries that need to be updated, please see below
40,Additional satellite report sequences,340018,(Altimeter product),,340193,Uuu,,,Operational
40,Additional satellite report sequences,340018,(Altimeter product),,340194,Vvv,,,Operational
40,Additional satellite report sequences,340018,(Altimeter product),,340195,www,,,Operational
40,Additional satellite report sequences,340018,(Altimeter product),,340196,Xxx,,,Operational

**Comment by erget** [comment]
I've corrected the issues found on the associated branch; it looks fine to me now.

**Comment by marijanacrepulja** [comment]
@erget I also found that lines below need to be updated
40,Additional satellite report sequences,340022,(Altimeter main values),,340023,Yyy,,,Operational
 40,Additional satellite report sequences,340022,(Altimeter main values),,340023,Yyy,,,Operational
 40,Additional satellite report sequences,340022,(Altimeter main values),,340023,Yyy,,,Operational
 40,Additional satellite report sequences,340022,(Altimeter main values),,340024,Zzz,,,Operational

**Comment by efucile** [comment]
replace 3-40-018 with 3-40-xxx before validation of samples

**Comment by erget** [comment]
I have renamed 3-40-018 to 3-40-019, giving precedence to #10.

**Comment by erget** [comment]
Hi @marijanacrepulja I've uploaded new [sample data](https://github.com/wmo-im/BUFR4/files/4813777/s6.tar.gz), can you please re-confirm?

**Comment by marijanacrepulja** [comment]
Hi @erget,  please see attached output of decoded sample. I have used table D from branch but haven't been able to check values, as there is no file to show what the decoded values should be.

[W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,S6A+P4+L2+HR_C_EUMS_20170305065123_F01_000_000_20170305065238.bin_decoded.txt](https://github.com/wmo-im/BUFR4/files/4825116/W_XX-EUMETSAT-Darmstadt.SURFACE%2BSATELLITE.S6A%2BP4%2BL2%2BHR_C_EUMS_20170305065123_F01_000_000_20170305065238.bin_decoded.txt)

I have now noticed with real numeration assigned, that template 3-40-023 “Altimeter main values” contains repetition of 3-40-24 three times. Could you please explain the reason.

I have request from our Research Department if could be possible to include 20-Hz wind speed values (21 of them).
Many thanks

**Comment by erget** [comment]
@marijanacrepulja thank you very much!

The repetition of 3-40-024 is due to the use of 3 different algorithms: SAR, LRM & PLRM. This was agreed (prior to my involvement!) with colleagues from ECMWF, I believe in R&D, but I'm not sure who was involved.

Also, although we have space in the sequence for including 20-Hz wind speed values, these are not present in the original product - Sentinel-6 doesn't produce them. That's why you don't see them in these BUFR messages.

Is there anything else we should discuss or can we consider the product validated?

**Comment by marijanacrepulja** [comment]
@erget I believe we can consider the product validated. Thank you for the feedback.

**Comment by erget** [comment]
Perfect, thank you, then I am marking this template as validated.

**Comment by amilan17** [comment]
SUMMARY: Add entry to Table B Class 21, add entry to Table B Class 22 and add entries to Table D Category 40.

**Comment by amilan17** [comment]
Approved by FT 2020-2.
