### ISSUE TITLE
BUFR Table for the variable Permafrost Temperature 

### ISSUE THREAD

**Issue by rodicanitu** [wmo-im/BUFR4#157]
### Details

Permafrost community (as supported through the Global Cryosphere Watch) is requesting the preparation of a BUFR Table for Permafrost Temperature, which is available from AWS operating in the Arctic, e.g. Svalbard Integrated Arctic Earth Observing System ([SIOS](https://sios-svalbard.org/). Topic lead: Dr Ketil Isaksen, ketili@met.no  
Additional description to be provided by Ketil

### Proposal

_update 11 July 2023_

Add sequence 3 07 064 (Soil temperature profile including permafrost)

<table><tbody><tr><td>FXY2</td><td>ElementName_en</td><td>ElementDescription_en</td></tr><tr><td>004025</td><td>Time period or displacement</td><td>&nbsp;</td></tr><tr><td>106000</td><td>Delayed replication of 6 descriptors</td><td>&nbsp;</td></tr><tr><td>031001</td><td>Delayed descriptor replication factor</td><td>&nbsp;</td></tr><tr><td>007061</td><td>Depth below land surface</td><td>&nbsp;</td></tr><tr><td>201131</td><td>Change data width</td><td>&nbsp;</td></tr><tr><td>202129</td><td>Change scale</td><td>&nbsp;</td></tr><tr><td>012130</td><td>Soil temperature</td><td>&nbsp;</td></tr><tr><td>201000</td><td>Change data width</td><td>Cancel</td></tr><tr><td>202000</td><td>Change scale</td><td>Cancel</td></tr></tbody></table>

Note: "Intended for recording permafrost, but can be applied for any soil temperature profile"

### Requestor

Ketil Isaksen (@KetilIsaksen), Norwegian Meteorological Institute, ketili@met.no  
Rodica Nitu (@rodicanitu), WMO/GCW

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.25.26.April.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.25.26.April.2023) notes: 

*   Anna will send an email to establish coordination

**Comment by KetilIsaksen** [comment]
I prepared some slides on permafrost measurements as a background for the discussion regarding what is needed from possible changes in BUFR tables and in order to hopefully reach some conclusions.
[Permafrost Temperature in BUFR.pdf](https://github.com/wmo-im/BUFR4/files/11372375/Permafrost.Temperature.in.BUFR.pdf)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023 notes: 
Ketil presented an overview

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2023.permafrost notes: 
Pal described the findings from creating a sample data file in the email sent on 12 May. (@amilan17 will copy to issue comments after).

**Comment by amilan17** [comment]
email copy circa 12 May: 
***
Dear colleagues,

We were asked to provide a sample of how permafrost temperature could be encoded in BUFR, and for this we have chosen the data set from our northernmost permafrost station 01002 Verlegenhuken of 06 UTC May 4th.

Please find attached the files:

wmo_1002-040600.bufr: This is the BUFR file produced internally at MET Norway for 01002 Verlegenhuken, and later included as subset 1 in the GTS bulletin ISMD38 ENMI 040600. Note that we are using the BUFR template (unexpanded descriptors in section 3) 307079 004025 011042 for all our land based stations, whether or not they are actually observing 011042 Maximum wind speed (10-minute mean wind).

wmo_1002-040600_permafrost.bufr: Here we have tried to encode also the 27 levels of permafrost temperature observed at Verlegenhuken, by adding the sequence 004025 104000 031001 202126 007061 202000 012130 to the set of unexpanded descriptors in section 3.

wmo_1002-040600.txt and wmo_1002-040600_permafrost.txt: Decoded contents of the two bufr files by use of [bufrread.pl](http://bufrread.pl/) from (the CPAN module) Geo::BUFR. 

Explanation of the added descriptor sequence in the permafrost BUFR file:

004025 Time period or displacement: Set to 0
106000 Delayed replication of 6 descriptors
031001 Delayed descriptor replication factor
007061 Depth below land surface
201131 Change data width: Add 3 bits
202129 Change scale operator: Add 1 to scale
012130 Soil temperature
202000 Change scale: Cancel
201000 Change data width: Cancel

Change of data width and scale for 012130 Soil temperature is regarded as necessary to obtain 3 decimal precision in temperature. Although the measurement systems currently in use generally provide an accuracy and precision of 0.1°C or better, 3 decimal in the data series is our preferred precision to better capture small, but significant long-term changes in permafrost temperature.

The first descriptor 004025 (set to 0) is not really part of the permafrost sequence, but necessary here to mark transition from 'period data section' to a new 'instantaneous data section'  in accordance with e.g.

B/C1.9 “Instantaneous” data required by regional or national reporting practices: If regional or national reporting practices require inclusion of additional “instantaneous” parameters, the sequence descriptor 3 07 080 shall be supplemented by the required element descriptors being preceded by a relevant time period descriptor set to zero, i.e. 0 04 024 = 0 or 0 04 025 = 0.

It is our current point of view that 012130 Soil temperature very well could be used also for permafrost temperature. There should be no need to include more metadata about permafrost temperature in the BUFR file we believe, better then to add such metadata in Oscar Surface for the station in question.
***

[wmo_1002-040600_permafrost.txt](https://github.com/wmo-im/BUFR4/files/11488418/wmo_1002-040600_permafrost.txt)
[wmo_1002-040600.txt](https://github.com/wmo-im/BUFR4/files/11488420/wmo_1002-040600.txt)

**Comment by sergioh-pessoal** [comment]
I decoded the available sample. The result is attached and is the same as the provided text. Version 31 was used for coding this sample. Therefore, the descriptor 3-07-064 was not used. I would like to ask. Does a new sample need to be produced? Including the new descriptor
[wmo_1002-040600_permafrost.bufr.decoded.txt.gz](https://github.com/wmo-im/BUFR4/files/11676293/wmo_1002-040600_permafrost.bufr.decoded.txt.gz)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023/) notes: 

DECISION on title: Keep current title "Soil temperature profile including permafrost" and add a comment indicating that it's not limited to only permafrost; 

note: "Intended for recording permafrost, but can be applied for any soil temperature profile"

**Comment by jbathegit** [comment]
I was able to decode both samples (with and without 004025) using NCEP's BUFR decoding software, and in both cases I got identical results to what was provided in the corresponding .txt files.  So I believe that makes for a successful validation, but note that this new 307064 sequence will eventually be part of version 41 of the tables, not version 40 which is already released.

As far as whether or not to include 004025 in the 307064 sequence, I don't have a strong opinion either way, but my personal vote would be to include it.

**Comment by sergioh-pessoal** [comment]
I also decoded both samples (with and without 004025) and get the same results using INPE bufr decoding.  
Regarding the inclusion or not of 004025 in the 307079,  I would also vote for inclusion

**Comment by amilan17** [comment]
All please review the issue summary. 

I updated it based on content in the branch. @marijanacrepulja there are some descriptions in this comment (https://github.com/wmo-im/BUFR4/issues/157#issuecomment-1576967231) that are not in the branch.

**Comment by sergioh-pessoal** [comment]
@amilan17 

I double-checked the table in the branch. And I decoded the sample again using the branch tables. The sample (with 0-04-025 included) was decoded without any problems and the result has exactly the same values as the provided text file


Reviewing the question of whether or not 0-04-025 should be included in 3-07-064. The best option is the one already in the tables. i.e. The 0-04-025 included in 3-07-064.

Reason: Ensures time period = 0 is being set

**Comment by marijanacrepulja** [comment]
> All please review the issue summary. 
> 
> I updated it based on content in the branch. @marijanacrepulja there are some descriptions in this comment ([#157 (comment)](https://github.com/wmo-im/BUFR4/issues/157#issuecomment-1576967231)) that are not in the branch.

@amilan17 I updated proposal to avoid confusion, the comments were just for info. Thanks for spotting this.
