### ISSUE TITLE
BUFR table B descriptors for atmospheric composition

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#160]
### Initial request

ECMWF is proposing a new BUFR table B descriptors to represent atmospheric composition observations.

### Amendment details

**1. Update CCT-11 that is linked to  0-01-035 for Originating centre**
|Code| Originating centre | 
|----|-----|
|293| University of Bremen|
|294| Netherlands Institute for Space Research (SRON) | 
|295| The Royal Belgian Institute for Space Aeronomy (BIRA-IASB)|
|296| The French National Centre for Scientific Research (CNRS)|
|297|The Nanjing Institute of Environmental Sciences (NIES)|
|298| Dynamic Meteorology Laboratory (LMD)|
|299| The Rutherford Appleton Laboratory  (RAL)

**2. Add a new elements  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-02-009 |MODIS aerosol algorithm| CODE TABLE | 0 | 0 | 4

**3. Add a new CODE/FLAG TABLE 0-02-009 for MODIS aerosol algorithm**
|Code| MODIS aerosol algorithm
|----|-----|
|0| Land corrected reflectances|
|1| Ocean best solution|
|2| Ocean average solution|
|3-14| Reserved
|15| Missing value

**4. Add a new elements  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-33-054 |Overall quality of retrieved atmospheric profile| Code table | 0 | 0| 3

**5. Add a new CODE/FLAG TABLE 0-33-054 for Overall quality of retrieved atmospheric profile**
|Code| Overall quality of retrieved atmospheric profile
|----|-----|
|0| Profile values good |
|1| Profile values suspected|
|2| Reserved|
|3| Profile values not good|
|4-6| Reserved|
|7| Missing|

**6. Add a new elements  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-20-079 |  Snow or ice crystals indicator| Code table | 0 | 0| 2

**7. Add a new CODE/FLAG TABLE 0-20-079 for Snow or ice crystals indicator**
|Code| Snow or ice crystals indicator
|----|-----|
|0| No snow or ice|
|1| Snow present|
|2| Reserved|
|3| Missing|

**8. Add a new elements  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-08-045 |  Character of particulate matter | Code table | 0 | 0| 8

**9. Add a new CODE/FLAG TABLE 0-08-045 for Character of particulate matter**
|Code| Character of particulate matter
|----|-----|
|0| Aerosols all types|
|1| Desert dust|
|2| Black carbon |
|3| Sea salt|
|4-254| Reserved|
|255| Missing|

**10. Add a new elements  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-15-043 | Number of averaging kernel layers| Numeric | 0 | 0| 10

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-15-044 |Averaging kernel value| Numeric | 6 | - 5000000| 31

### Requestor(s)

Roberto Ribas, Marijana Crepulja (both from ECMWF)

### Stakeholder(s)

Copernicus Atmosphere Monitoring Service

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR table B

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2%263May.2023 notes:
Marijana presented proposal; Jeff pointed out that there are originators in the main table that are not national centers...

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023 notes:
0-01-035 has more space;

**Comment by marijanacrepulja** [comment]
Hi @amilan17, I have updated the branch. Could you please check and move it to ready for FT.

I have realised that entries for 0-01-035  Originating centre is linked to Common Code Table C-11. Therefore I have to create an issue under CCT in order to update C11.csv file

**Comment by amilan17** [comment]
*   For consistency with "20022,Character of precipitation" and "020026,Character of obscuration" I recommend changing 008045 to "Character of particulate matter"

**Comment by marijanacrepulja** [comment]
> * For consistency with "20022,Character of precipitation" and "020026,Character of obscuration" I recommend changing 008045 to "Character of particulate matter"
> * CODE/FLAG TABLE 0-20-079: Do we need to indicate that ice crystals are present or just snow?

@amilan17  As for entries in 0-20-079, these values are required for now, we made name generic for the future use of the table

**Comment by marijanacrepulja** [comment]
[sample_for_descriptors.tar.zip](https://github.com/wmo-im/BUFR4/files/12103460/sample_for_descriptors.tar.zip)

Hi @jbathegit, I have uploaded the sample. 

Many thanks for your help with validation.

**Comment by SibylleK** [comment]
Here the output of the DWD BUFR reading software:
[sample_for_descriptors.bufr.DWDreadbufrxOutput.zip](https://github.com/wmo-im/BUFR4/files/12105172/sample_for_descriptors.bufr.DWDreadbufrxOutput.zip)

The values are the same as in sample_for_descriptors.bufr.txt.

There is a typo in BUFRCREX_TableB_en_15.csv for the reference value of 015044. It should be written without a space. (-5000000 instead of - 5000000)

Otherwise, in my view, the validation is done.
