### ISSUE TITLE
Retirement of CREX

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/BUFR4#180]
### Details

This Issue is intended to stimulate discussion about the “retirement of CREX”.

The FM 95-XIV CREX – Character form for the representation and exchange of data was developed parallel to FM 94 BUFR as part of the migration to Table-driven Code Forms (TDCF).

The “A Word from the Fourteenth WMO Congress” ([A Word From Cg-XIV | World Meteorological Organization (wmo.int)](https://community.wmo.int/en/activity-areas/wmo-codes/mtdcf/word-cg-xiv)) states: 
“b.   The use of CREX was an interim step in the migration to BUFR;”

As CREX should only be an interim solution for members not able to produce and handle BUFR, it might be time to discuss whether the FM 95-XIV CREX should retire.

CREX is propably no longer needed, For example, most of the newly exchanged messages on WIS2.0 are BUFR edition 4.

However, there are still some CREX messages send around on GTS.
An extract from a DWD routing catalog:
"KSAA30 KWBC","EGRR","****","2GIS","EDZW"
"KSAA30 KWBC","RUMS","****","2GIS","EDZW"
"KSAA30 KWBC","EGRR","****","2GIS","EDZW"
"KSAA31 KWBC","EGRR","****","2GIS","EDZW"
"KSAA31 KWBC","RUMS","****","2GIS","EDZW"
"KSAA31 KWBC","EGRR","****","2GIS","EDZW"
"KSAA32 KWBC","EGRR","****","2GIS","EDZW"
"KSAA32 KWBC","RUMS","****","2GIS","EDZW"
"KSAA32 KWBC","EGRR","****","2GIS","EDZW"
"KSAB30 KWBC","EGRR","****","2GIS","EDZW"
"KSAB30 KWBC","RUMS","****","2GIS","EDZW"
"KSAB30 KWBC","EGRR","****","2GIS","EDZW"
"KSAB31 KWBC","EGRR","****","2GIS","EDZW"
"KSAB31 KWBC","RUMS","****","2GIS","EDZW"
"KSAB31 KWBC","EGRR","****","2GIS","EDZW"
"KSAB32 KWBC","EGRR","****","2GIS","EDZW"
"KSAB32 KWBC","RUMS","****","2GIS","EDZW"
"KSAB32 KWBC","EGRR","****","2GIS","EDZW"
"KSAB33 KWBC","EGRR","****","2GIS","EDZW"
"KSAB33 KWBC","RUMS","****","2GIS","EDZW"
"KSAB33 KWBC","EGRR","****","2GIS","EDZW"
"KSAE30 KWBC","EGRR","****","2GIS","EDZW"
"KSAE30 KWBC","RUMS","****","2GIS","EDZW"
"KSAE30 KWBC","EGRR","****","2GIS","EDZW"
"KSAF30 KWBC","EGRR","****","2GIS","EDZW"
"KSAF30 KWBC","RUMS","****","2GIS","EDZW"
"KSAF30 KWBC","EGRR","****","2GIS","EDZW"
"KSAG30 KWBC","EGRR","****","2GIS","EDZW"
"KSAG30 KWBC","RUMS","****","2GIS","EDZW"
"KSAG30 KWBC","EGRR","****","2GIS","EDZW"
"KSAJ30 KWBC","EGRR","****","2GIS","EDZW"
"KSAJ30 KWBC","RUMS","****","2GIS","EDZW"
"KSAJ30 KWBC","EGRR","****","2GIS","EDZW"
"KSCD40 UGEE","RUMS","****","2GIS","EDZW"
"KSRS03 EUMS","EUMS","****","2GIS","EDZW","HKNC"
"KSRS08 EUMS","EUMS","****","2GIS","EDZW","HKNC"
"KSRS42 EUMS","EUMS","****","2GIS","EDZW","EUMS","HKNC"
"KSXD40 OKPR","OKPR","****","2GIS","DEMS","EDZW","EGRR","LTAA","RKSL","RUMS"
"KSXD40 OKPR","RUMS","****","2GIS","DEMS","EDZW","EGRR","LTAA","RKSL","RUMS"
"KULC02 RJTD","RJTD","****","2GIS","EDZW"
"KULC02 RJTD","RUMS","****","2GIS","EDZW"
"KULC02 RJTD","NOAA","****","2GIS","EDZW"
"KULI02 EGRR","LFPW","****","2GIS","EDZW"
"KULI02 SABM","FMMA","****","2GIS","EDZW"
"KULI03 EGRR","LFPW","****","2GIS","EDZW"
"KULI03 SABM","FMMA","****","2GIS","EDZW"
"KULL01 RJTD","RJTD","****","2GIS","EDZW"
"KULL01 RJTD","RUMS","****","2GIS","EDZW"
"KULL01 RJTD","NOAA","****","2GIS","EDZW"

i.e.: 
KSA  01-29 Routinely scheduled observations for distribution from automatic (fixed or mobile) land stations.
KSA  30-59 N-minute observations from automatic (fixed or mobile) land stations
KSC Climatic observations 
KSR Hydrologic reports
KSX Other surface data (IAC,IAC FLEET)
and
KUL Total ozone

are produced and distributed.

Therefore, it should be investigated first, who processes this CREX data and relies on it.

The team is requested to discuss this issue and decide whether and if so in which way CREX should retire.

### Requestor

Sibylle Krebber(DWD) @SibylleK

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023](https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023)

the team agreed to move towards the retirement of CREX

**Comment by amilan17** [comment]
- [ ] write proposal for INFCOM-3
- [ ] Investigate the impact of removing the CREX columns on software used in Africa; (Abderezak)

**Comment by amilan17** [comment]
INFCOM-3 approved the recommendation for EC. 
https://meetings.wmo.int/INFCOM-3/_layouts/15/WopiFrame.aspx?sourcedoc={F63B99F0-BA54-4014-8C9B-94089B3DBF44}&file=INFCOM-3-d08-3(7)-AMENDMENTS-MANUAL-ON-CODES-approved_en.docx&action=default
