### ISSUE TITLE
Update BUFRCREX_TableB_en_040.csv:  Lidar L2b classification type

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#181]
### Initial request

ECMWF is proposing new entries in the table B code/flag table for Lidar L2b classification type needed for aerosol Aeolus observations. That is in support of NWP data assimilation.

### Amendment details

**1. Update CODE/FLAG TABLE 040036 for  Lidar L2b classification type**
|Code| Lidar L2b classification type
|----|-----|
|2| Aerosol|
|3| Attenuated|
|4| Surface|
|5-14| Reserved|

### Requestor(s)

Marijana Crepulja. Roberto Ribas, Angela Benedetti (all from ECMWF)

### Stakeholder(s)

ESA
KNMI
Meteo France
ECMWF member sates 

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR code table 0 40 036

### Expected impact of change

None

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023](https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023) notes: 

team agrees to proposal

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated branch. Please check and move to ready for FT.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
@amilan17 validate branch
