### ISSUE TITLE
Update BUFRCREX_CodeFlag_en_01.csv Retrieval identifier

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#182]
### Initial request

ECMWF is proposing new entries in the table B code/flag table Retrieval identifier needed for aerosol Aeolus observations. That is in support of NWP data assimilation.

### Amendment details

**1. Update CODE/FLAG TABLE 001155 Retrieval identifier**
|Code| Retrieval identifier
|----|-----|
|6| Maximum Likelihood Estimation – High horizontal resolution (MLEsub)|
|7-254| Reserved|

### Requestor(s)

Marijana Crepulja. Roberto Ribas, Angela Benedetti, Karen Henry (all from ECMWF)

### Stakeholder(s)

ESA
KNMI
Meteo France
ECMWF member sates

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR code table 001155

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023)

team agrees to proposal

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated the branch. Please review and move to Ready for FT.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
@amilan17 validate branch

**Comment by amilan17** [comment]
@marijanacrepulja for my understanding, can you explain the "sub" part of MLEsub?

**Comment by marijanacrepulja** [comment]
@amilan17 
The MLE retrieval has results at the BRC (basic repeat cycle) level, whereas the MLEsub has the MLE results at a higher resolution. So values are for a shorter distance.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023) notes:

branch is ready for validation

**Comment by amilan17** [comment]
@amilan17 - to validate
