### ISSUE TITLE
New BUFR entries for representing ASCAT in BUFR

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#184]
### Initial request

The team is kindly invited to review proposal for inclusion into new version of BUFR tables. 

### Amendment details

In support to data assimilation of ASCAT observations, there is a need to define new BUFR descriptors for 
subsurface scattering regime and subsurface scattering probability. The data should include the surface flag which is defined as 013040. 

The BUFR Template for ASCAT already exists as 312061. 

The team will discuss how to proceed further. Do we need a new BUFR template, or we can use existing one and add descriptors for surface flag and  subsurface scattering probability.

As for  subsurface scattering regime, that will be available later, this should be confirmed with data provider.  

**1. Add new element in class 21**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0 21 167 |Subsurface scattering probability|% | 0 | 0 | 7

Update 013040 with frozen soil 

**2. Update CODE/FLAG TABLE 013040 Surface flag**
|Code| Lidar L2b classification type
|----|-----|
|12| Frozen soil|
|13-14| Reserved|

### Requestor(s)

GeoSphere Austria

### Stakeholder(s)

UK Met Office
ECMWF

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR table B and D

### Expected impact of change

MEDIUM

### Collaborators

EUMETSAT, ECMWF

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023) notes: 

Giannokos and Sebastien, from Geosphere, introduced BUFR issue #184; the team discussed options and decided to add the two new descriptors to the end of 3 12 061

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes: 
- to provide sample data soon for validation by the end of the month

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023) notes:

still waiting for sample data

**Comment by marijanacrepulja** [comment]
[ascat_sample.zip](https://github.com/wmo-im/BUFR4/files/13685335/ascat_sample.zip)

A sample BUFR file is attached along with output of decoding.

**Comment by amilan17** [comment]
Marijana decoded; @amilan17 validate branch
