### ISSUE TITLE
New table B descriptor for a sensor identifier

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/BUFR4#19]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue-19

# Summary and purpose
If several measurements are available for a parameter at the same height and at the same time, an identifier is required for the individual measurements. A new descriptor for a sensor identifier is proposed. 

# Action proposed
The team is requested to review and to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
With regard to the measurement on high towers, e.g. of ICOS ecosystem stations, some parameters are measured in different orientations to take into account the influence of the tower.
In addition to the orientation (bearing or azimuth), an identifier of the sensor is also required. It is needed e.g. to link more metadata to the specific measurements. 
Therefore a simple sensor identifier is proposed.

# Detailed proposal

Add a new descriptor to BUFR Table B
|FXY|ElementName_en             |Note_en |BUFR_Unit |BUFR_Scale |BUFR_ReferenceValue |BUFR_DataWidth_Bits|CREX_Unit|CREX_Scale|CREX_DataWidth_Char|
|---|---|--|--|--|--|--|--|--|--|
|001154| Sensor identifier| | Numeric| 0| 0| 12 | Numeric | 0| 4|

**Comment by jbathegit** [comment]
Is there any reason existing descriptor 0-01-050 (Platform transmitter ID number) couldn't be used for this purpose?

If a new descriptor is added, it would need a different number besides 0-01-152, because that number is already assigned for "Semi-major axis of rotation ellipsoid".

**Comment by SibylleK** [comment]
Thank you very much Jeff, the number is changed to 0-01-154 now.

**Comment by chenxiaoxia2019** [comment]
@SibylleK Hi, Sibylle, I created a branch for this issue. Could you please check it? Thanks.

**Comment by SibylleK** [comment]
Thank you very much @chenxiaoxia2019, I found the new entry for a sensor identifier in the new branch. 
Please excuse all the close, reopens and moves...

**Comment by SibylleK** [comment]
An example with sensor identifier was created with DWD BUFR software and by using the branch.
SensorIdentification.bufr_decoded shows the output of DWD decoding software.

[SensorIdentification.zip](https://github.com/wmo-im/BUFR4/files/4745088/SensorIdentification.zip)

**Comment by jbathegit** [comment]
Hi @SibylleK - I was able to successfully decode your sample message using our NCEP BUFRLIB software, and all of my decoded values matched those in your .bufr_decoded file.

**Comment by SibylleK** [comment]
@jbathegit Thank you very much for your support.
@efucile, @chenxiaoxia2019 What else is needed for a successful validation of the new descriptor, or is the decoding of two independent software already sufficient in this case?

**Comment by SibylleK** [comment]
I have added the samples validated label to note that some validation was done. I cannot participate at the next meeting on 22th June, but I hope the validation is sufficient to include the new entry in the next Fast-Track procedure.

**Comment by amilan17** [comment]
Approved by FT-2020-2
