### ISSUE TITLE
New BUFR Template for Snow Surface Temperature

### ISSUE THREAD

**Issue by rodicanitu** [wmo-im/BUFR4#196]
### Details

I'm submitting the request expressed by the Expert Team on Snow Watch of AG-GCW, for the generation of a new BUFR Template for Snow Surface Temperature (or expansion of an existing sequence, as the case may be). 
The scientific lead of the issue is Dr Charles Fierz, fierz@slf.ch, who will connect with MeteoSwiss on the data exchange aspects.
Ran Zhang (rzhang@wmo.int) will support Charles, from the Secretariat.
Thank you.
Rodica Nitu

### Requestor

Anna Milan (WMO), @amilan17

**Comment by amilan17** [comment]
replaced by new issue.
