### ISSUE TITLE
new code figure for BUFR Table B 0-02-080

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/BUFR4#197]
Related to [CCT #196](https://github.com/wmo-im/CCT/issues/196), we would also like to request a new entry in the code table for descriptor 0-02-080, as noted below.

### Amendment details

BUFR Table B 0-02-080 "Balloon manufacturer"
Code figure | Meaning
:-----: | -------- 
5 | WindBorne

### Requestor(s)

Jeff Ator (NOAA)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR Table B descriptor 0-02-080

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes:
Jeff introduced the proposal;

**Comment by jbathegit** [comment]
The development branch is now updated

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
branch is ready for validation

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
tied to #197, not BUFR sequences yet

**Comment by jbathegit** [comment]
> https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes: tied to #197, not BUFR sequences yet

Correct, at this time we aren't proposing a new Table D descriptor sequence for this data, but perhaps we will at some point in the future.

In the meantime, the new subtype re: [CCT #196](https://github.com/wmo-im/CCT/issues/196) is more than sufficient to clearly identify what type of data this is.
