### ISSUE TITLE
Update GitHub actions

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#199]
### Details
From what I understand, the check can fail for two reasons.

The TXT and XML is already generated in branch and there are no changes.
Branch protections on master prevents automated updates.
I think the actions should follow the logic as determined in https://github.com/wmo-im/CCT/issues/197.

### Requestor

Anna Milan (WMO), @amilan17

**Comment by amilan17** [comment]
@antoinemerle will fix

**Comment by antoinemerle** [comment]
HI @amilan17 , fixed in  a5bea68e9940dd1d460b254c30e570b9b15dca3c
🎊
