### ISSUE TITLE
Tropical cyclone tracks, wind radii and vortex

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#201]
### Initial request

With the reference to the (https://meetings.wmo.int/INFCOM-3/_layouts/15/WopiFrame.aspx?sourcedoc=%7B964360a3-5884-4443-8c5b-b8b6ebca9b12%7D&action=view&wdAccPdf=0&wdparaid=6AED0856)

TT-TCPara have requested a new BUFR template for tropical cyclone to include new vortex variables. 

### Amendment details

**1. Add a new element  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-01-130 |Storm identifier (long) |CCITT IA5| 0| 0 | 32

**2. Add a new elements  in table B** 
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-11-024 | Average u component after the vortex removal|m/s | 1| -4096 | 13
0-11-025 | Average v component after the vortex removal|m/s | 1| -4096 | 13

**3. Add a new table B descriptor 0-08-055 for Method used to calculate  the average wind components after removing vortex**
F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-08-055 | Method used to calculate the average wind components after removing vortex | Code table| 0 | 0 | 4

**4. Add a new CODE/FLAG TABLE 0-08-055 for Method used to calculate the average wind components after removing vortex**
|Code|  Method used to calculate the average wind components after removing vortex| 
|----|-----| 
|0| Calculate the area average of the u and v components at pressure levels from 0 to 500km centred on the surface vortex position
|1| Calculate the area average of the u and v components at pressure levels from 0 to radius greater than 500km centred on the surface vortex position|
|2-14| Reserved
|15| Missing value

NOTE: Method used to calculate average wind components after removing vortex is described in Knaff et al. (2009)

**5. Add a new template  in table D**

| Table Reference  F X Y |	F  X  Y| ELEMENT NAME| DESCRIPTION
| :-------------: |---|----|-----| 
|  | (Tropical cyclone track, wind radii and vortex ) | | |
|3 16 083|0 01 033|	Identification of Originating/generating Centre|
||0 01 034|	Identification of Originating/generating Centre Sub-Centre|
||0 01 032	|Generating application|
||0 01 130   |	Storm identifier (long)| 
||0 01 027|	WMO long storm name|
|| 0 01 030 |   Numerical model identifier
||0 01 090|    Technique for making up initial perturbations|
||0 01 091|	Ensemble member number|
||0 01 092	|Type of ensemble forecast|
||3 01 011	|Year, month, day|
||3 01 012|	Hour, minute|
||0 08 005|	Meteorological attribute significance|
||3 01 023	|Latitude/longitude (coarse accuracy)|
||0 08 005|	Meteorological attribute significance|
||3 01 023|	Latitude/longitude (coarse accuracy)|
||0 10 051|	Pressure reduced to mean sea level|
||0 08 005	|Meteorological attribute significance|
||3 01 023|	Latitude/longitude (coarse accuracy)|
||0 11 012	|Wind speed at 10 m|
||1 07 004|      Replicate 7 descriptors 4 times
||0 19 003	|Wind speed treshhold|
||1 05 004|	Replicate 5 descriptors 4 times|
||0 05 021	|Bearing or azimuth|
||0 05 021|	Bearing or azimuth|
||2 01 131	|Change data width|
||0 19 004|	Effective radius with respect to wind speeds above threshold|
||2 01 000	|Change data width | Set to missing (cancel)
||1 16 000|	Delayed replication of 16 descriptors| 
||0 31 001	|Delayed descriptor replication factor|
||0 08 021|	Time significance|
||0 04 024	|Time period or displacement|
||0 08 005|	Meteorological attribute significance|
||3 01 023	|Latitude/longitude (coarse accuracy)|
||0 10 051|	Pressure reduced to mean sea level|
||0 08 005	|Meteorological attribute significance|
||3 01 023	|Latitude/longitude (coarse accuracy)|
||0 11 012|	Wind speed at 10 m|
||1 07 004|	Replicate 7 descriptors 4 times|
||0 19 003	|Wind speed threshold|
||1 05 004|	Replicate 5 descriptors 4 times|
||0 05 021	|Bearing or azimuth|
||0 05 021|	Bearing or azimuth|
||2 01 131	|Change data width|
||0 19 004|	Effective radius with respect to wind speeds above threshold|
||2 01 000	|Change data width | Set to missing (cancel)
|| 1 04 000| Delayed replication of 4 descriptors|
|| 0 31 001| Delayed descriptor replication factor|
|| 0 08 055 | Method used to calculate the average wind components after removing vortex
|| 0 07 004| Pressure|
|| 0 11 024 | Average u component after the vortex removal|
|| 0 11 025 | Average v component after the vortex removal

### Requestor(s)

TT-TCPara 
Marijana Crepulja (ECMWF)
Fernando Prates (ECMWF)

### Stakeholder(s)

WMO member states

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, BUFR code table 0 20 009

### Expected impact of change

MEDIUM

### Collaborators

ECMWF

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes: 
Marijana introduced the proposal; Jeff suggested using the storm identifier and making it longer with a 208 operator; Anna noted that their description for the storm identifier differs from the note 1 in Table B.

**Comment by amilan17** [comment]
WIPPS Guide states: "The storm identifier is a 4-character string, with the first 3 characters being numbers and the last being a capital letter."
MoC note states: "The storm identifier (descriptor 0 01 025) has the following meaning: the first two characters shall be a numeric sequence number assigned by the originator of the message; the third character is a letter indicating the ocean basin..."

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes: 
Marijana made some updates to the proposal

**Comment by amilan17** [comment]
@marijanacrepulja should there also be a note added to 3 16 082 to indicate that this new template should be used instead?

**Comment by amilan17** [comment]
I spoke with my colleauge in the Secretariat who is supporting that team and she said: "TCPara decided to expand to four characters to take in pre-genesis phase of cyclone tracks .... to distinguish the existing analysis position (001-099) and new analysis position from the RSMC (100-999)"

**Comment by marijanacrepulja** [comment]
I spoke with my colleague who is a member of TCPara and he explained that 
In case of tropical depression e.g. using 3 characters for identification   
Storm identifier = 0ZW
Storm name = 0ZW

Splitting Storm identifier into two parts, numerical and letter would not be necessary as the storm identifier is used as a whole. Additionally the range up to 999 numbers is sufficient.

Therefore, one new descriptor for Storm identifier is preferred.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
Rename new code to "storm identifier (long)"; Marijana will update the branch and prepare sample data

**Comment by marijanacrepulja** [comment]
[tropical_cyclone_vortex.zip](https://github.com/user-attachments/files/15991332/tropical_cyclone_vortex.zip)

@shirley-xuelei please find attched zip file that contain sample BUFR file and txt file as output of decoding. Hope you will be able to validate the data. Many thanks.

I have updated the branch.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes
@shirley-xuelei and @sergioh-pessoal to validate the samples

**Comment by shirley-xuelei** [comment]
> [tropical_cyclone_vortex.zip](https://github.com/user-attachments/files/15991332/tropical_cyclone_vortex.zip)
> 
> @shirley-xuelei please find attched zip file that contain sample BUFR file and txt file as output of decoding. Hope you will be able to validate the data. Many thanks.
> 
> I have updated the branch.

@marijanacrepulja @amilan17 The data was validated, and please find the decoded file attached.  I randomly checked some element values and didn't find any problems, and there are two suggestions for #201 for your reference.
1. The unit of 0-08-055 should be 'Code table', other than 'Numeric'. 
2. The element name of '1 07 003' and '1 05 004'  is not supposed to be 'Delayed replication of x descriptors'.
[tropical_cyclone_vortex_dec.zip](https://github.com/user-attachments/files/16121620/tropical_cyclone_vortex_dec.zip)

**Comment by amilan17** [comment]
@marijanacrepulja please let me know when you've updated the branch per Lei's review. thx.

**Comment by etoyoda** [comment]
Two questions, if I'm allowed to make:
1. Really trivial: did you intend "_threshold_" for the element name of 0 19 003 "Wind speed _treshhold_" ?
2. Number of wind speed thresholds: did you intend to plase _0 19 004_ in place of _0 19 003_ ?
Approved amendment to the WIPPS Manual, EC-78/Doc.4.1.2(6) reads "Quadrant radii of sustained 10 m-winds of 28/34/502/64 kt".  We are supposed to provide radii for four (not three) thresholds, if I'm taking right.

**Comment by marijanacrepulja** [comment]
@etoyoda Thank you very much for your valuable comments.

We intended "threshold" for the element name of 0 19 003 "Wind speed treshhold".

I have updated the BUFR template to allow reporting for four thresholds. Please see
<!DOCTYPE html>
1 07 004 | Replicate 7 descriptors 4 times |  
-- | -- | --
  | 0 19 003 | Wind speed threshold |  
  | 1 05 004 | Delayed replication of 5 descriptors |  
  | 0 05 021 | Bearing or azimuth |  
  | 0 05 021 | Bearing or azimuth |  
  | 2 01 131 | Change data width |  
  | 0 19 004 | Effective radius with respect to wind speeds above threshold |  
  | 2 01 000 | Change data width | Set to missing (cancel)

**Comment by marijanacrepulja** [comment]
[tropical_cyclone_vortex_latest.zip](https://github.com/user-attachments/files/16511765/tropical_cyclone_vortex_latest.zip)

**Comment by marijanacrepulja** [comment]
@shirley-xuelei Thank you very much for validating the samples and your valuable comments. I have updated branch/proposal accordingly. 
@etoyoda has made a valuable comment that we should report for four thresholds as defined in WIPPS Manual.
I have updated a proposal/branch and provided new samples.

**Comment by sergioh-pessoal** [comment]
@marijanacrepulja
I’ve decoded the sample successfully with MBUFRTOOLS, and compare the results with text provided. The results are equivalent, and have same values for all variables.
So the template is valid
Please, find attached the decoded text file 
[tropical_cyclone_vortex_latest.decoded.txt.gz](https://github.com/user-attachments/files/16567157/tropical_cyclone_vortex_latest.decoded.txt.gz)

**Comment by marijanacrepulja** [comment]
@sergioh-pessoal Many thanks for your valuable and prompt help with validation!

**Comment by shirley-xuelei** [comment]
[tropical_cyclone_vortex_latest_dec.zip](https://github.com/user-attachments/files/16597096/tropical_cyclone_vortex_latest_dec.zip)
@marijanacrepulja I also validated the new template using our software , and it is valid. Please find the decoded file attached.

**Comment by marijanacrepulja** [comment]
@shirley-xuelei Thank you very much for your valuable support with validate. I really appreciate it.
