### ISSUE TITLE
Request of clarification regarding recent weather in SYNOP

### ISSUE THREAD

**Issue by efucile** [wmo-im/BUFR4#28]
We are writing to seek WMO’s clarification on the above subject.
 
2. As contained in Manual on Codes (WMO-No. 36), the weather phenomenon reporting code for surface observation, SYNOP is represented by group 7wwW1W2 that indicates “If more than one form of weather is observed, the highest applicable code figure shall be selected for the group 7wwW1W2.”
 
3. In accordance with WMO standard practices, we would appreciate it if WMO could help to clarify the following scenario of observation:
 

 
![image](https://user-images.githubusercontent.com/24636879/85276976-e80aee00-b482-11ea-8884-15a32c886836.png)
 
 

 
As depicted in the figure above, showers was started at 16.05 and closed at 17.05, while rain was started at 17.05 and closed at 17.30. In this regard, what is the code ww to be reported at 18.00? Is it 25 or 21 for ww?

**Comment by efucile** [comment]
@wmo-im/tdcf I just received this request. I think that we should answer that SYNOP is obsolete and point to B/C regulations. Is anyone able to answer the question using B/C regs?

**Comment by amilan17** [comment]
@jitsukoh @efucile  -- is this issue still relevant? should we close it?

**Comment by Darkholz** [comment]
The number to be used at 1800 is 25, because you will use the largest number. Since you have two options, you go for the largest number.

**Comment by amilan17** [comment]
Closing this because it's out of scope for the TT-TDCF work on GRIB and BUFR.
