### ISSUE TITLE
Add perturbed forecast in table 0-01-092

### ISSUE THREAD

**Issue by efucile** [wmo-im/BUFR4#3]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue-3

# Summary and purpose
This document proposes new entry to Code Tables 0 01 092 in order to represent forecasted tropical cyclone from ensemble forecast system.

# Action proposed
The team is kindly asked to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
Tropical cyclone size forecasts became available within the new ECMWF model operational implementation in addition to the existing track and intensity forecast. In order to allow forecasted tropical cyclone data representation from ensemble forecast system, additional entry is required in Code Table 0 01 092.

# Detailed proposal

Add the following element to Code table 0 01 092

Type of ensemble forecast
	Code figure

       4                Perturbed forecast

**Comment by efucile** [comment]
I am just copying the table from the repository to have a view of what is the impact of the request on the entire table.

001092 | Type of ensemble forecast | 0 | Unperturbed high-resolution control forecast |   |   |   | Operational
-- | -- | -- | -- | -- | -- | -- | --
  | 001092 | Type of ensemble forecast | 1 | Unperturbed low-resolution control forecast |   |   |   | Operational
  | 001092 | Type of ensemble forecast | 2 | Negatively perturbed forecast |   |   |   | Operational
  | 001092 | Type of ensemble forecast | 3 | Positively perturbed forecast |   |   |   | Operational
  | 001092 | Type of ensemble forecast | 4-191 | Reserved |   |   |   | Operational
  | 001092 | Type of ensemble forecast | 192-254 | Reserved for local use |   |   |   | Operational
  | 001092 | Type of ensemble forecast | 255 | Missing value

**Comment by chenxiaoxia2019** [comment]
@marijanacrepulja Hi, Marijana, I have created a branch for this issue. Could you please check the branch?

**Comment by marijanacrepulja** [comment]
@chenxiaoxia2019 Thank you very much for creating the branch. The addition to CodeFlag table is correct and I am able to use it in updating tables locally.

**Comment by amilan17** [comment]
SUMMARY: Add entry to Code Table 0-01-092.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
