### ISSUE TITLE
New BUFR sequence for tropical cyclone tracks

### ISSUE THREAD

**Issue by efucile** [wmo-im/BUFR4#4]
# Summary and purpose
ECMWF proposes a new BUFR sequence in order to represent tropical cyclone tracks, intensity and wind thresholds radii from ensemble forecast system.

# Action proposed
The team is kindly asked to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
The continuing model upgrades and more recently re-tuning of the Charnock parameter for very high wind speed has a positive impact in the wind field around the tropical cyclones, motivated the work to introduce the tropical cyclones wind radii forecasts in operations.
Tropical cyclone size forecasts became available with the new ECMWF model operational implementation in addition to the existing track and intensity forecasts. The size of the tropical cyclone is represented by the 34, 50 and 64kt wind thresholds radii (largest distance from the centre of the cyclone of a particular wind speed) in each of the four quadrants; NE, SE, SW and NW sectors.

The wind radii forecast is included in the same BUFR message that contains the information about the track and intensity. The users will be able to extract from the same message the position (latitude/longitude), intensity (minimum MSLP and maximum wind speed) and the wind thresholds radii from ensemble forecast system. 

# Detailed proposal

## New Table D Entries

__*Category 16: Synoptic feature sequences*__

(Tropical cyclone tracks and wind radii)

	
| Table Reference  F X Y |	F  X  Y| ELEMENT NAME|
| :-------------: |---|----|
|  | (Tropical cyclone track and wind radii) | | |
|3 16 082|0 01 033|	Identification of Originating/generating Centre|
||0 01 034|	Identification of Originating/generating Centre Sub-Centre|
||0 01 032	|Generating application|
||0 010 25|	Storm identifier|
||0 01 027|	WMO long storm name|
||0 01 090|Technique for making up initial perturbations|
||0 01 091|	Ensemble member number|
||0 01 092	|Type of ensemble forecast|
||3 01 011	|Year, month, day|
||3 01 012|	Hour, minute|
||0 08 005|	Meteorological attribute significance|
||3 01 023	|Latitude/longitude (coarse accuracy)|
||0 08 005|	Meteorological attribute significance|
||3 01 023|	Latitude/longitude (coarse accuracy)|
||0 10 051|	Pressure reduced to mean sea level|
||0 08 005	|Meteorological attribute significance|
||3 01 023|	Latitude/longitude (coarse accuracy)|
||0 11 012	|Wind speed at 10 m|
||1 07 003|	Delayed replication of 7 descriptors|
||0 19 003	|Wind speed treshhold|
||1 05 004|	Delayed replication of 5 descriptors|
||0 05 021	|Bearing or azimuth|
||0 05 021|	Bearing or azimuth|
||2 01 131	|Change data width|
||0 19 004|	Effective radius with respect to wind speeds above threshold|
||2 01 000	|Change data width (Cancel - set to missing) |
||1 16 000|	Delayed replication of 16 descriptors| 
||0 31 001	|Delayed descriptor replication factor|
||0 08 021|	Time significance|
||0 04 024	|Time period or displacement|
||0 08 005|	Meteorological attribute significance|
||3 01 023	|Latitude/longitude (coarse accuracy)|
||0 10 051|	Pressure reduced to mean sea level|
||0 08 005	|Meteorological attribute significance|
||3 01 023	|Latitude/longitude (coarse accuracy)|
||0 11 012|	Wind speed at 10 m|
||1 07 003|	Delayed replication of 7 descriptors|
||0 19 003	|Wind speed threshold|
||1 05 004|	Delayed replication of 5 descriptors|
||0 05 021	|Bearing or azimuth|
||0 05 021|	Bearing or azimuth|
||2 01 131	|Change data width|
||0 19 004|	Effective radius with respect to wind speeds above threshold|
||2 01 000	|Change data width (Cancel - set to missing)|

**Comment by marijanacrepulja** [comment]
Sample tropical cyclone wind radii messages are available for validation  as file ending in ".bufr" The corresponding ".bufr.decoded" file show what the decoded values should be.

[tc_windradii.zip](https://github.com/wmo-im/BUFR4/files/4750649/tc_windradii.zip)

**Comment by jbathegit** [comment]
Hi @marijanacrepulja - I was able to successfully decode your sample message using our NCEP BUFRLIB software.  I spot-checked most of my decoded values, and they all appeared to match those in your .bufr_decoded file.

**Comment by jitsukoh** [comment]
@marijanacrepulja Marijana, would you like to include the addition of table D descriptor 3 16 082 in FT-2020-2 procedure? It's not on the list of today's meeting at the moment but I think it's ready...

**Comment by marijanacrepulja** [comment]
@jitsukoh Jitsuko, yes please. It is validated and ready for FT-2020-2. Many thanks.

**Comment by marijanacrepulja** [comment]
Hi @chenxiaoxia2019, could you please make a branch for this issue, so it can be merge in master branch for FT2020-2. Many thanks.

**Comment by chenxiaoxia2019** [comment]
@marijanacrepulja Hi, Marijana, a new branch for this issue has been created: https://github.com/wmo-im/BUFR4/tree/issue-4. Could you please check it? Thanks. Sorry for belated reply.

**Comment by marijanacrepulja** [comment]
@chenxiaoxia2019 Thanks a lot! All look good to me.

**Comment by amilan17** [comment]
SUMMARY: Add entries to Table D Category 16.

**Comment by amilan17** [comment]
Approved by FT-2020-2

**Comment by amilan17** [comment]
@marijanacrepulja 

We are preparing the manual for publication and noticed an inconsistency with other codes in Table D16. Can you confirm that this edit doesn't change the original meaning of 2 01 000? 

<table><tbody><tr><td><strong>Table Ref</strong></td><td><strong>Element Name</strong></td><td><strong>Element Description</strong></td></tr><tr><td>2 01 000</td><td>Change data width <s>(Cancel - set to missing)</s></td><td>Set to missing (cancel)</td></tr></tbody></table>

**Comment by marijanacrepulja** [comment]
@amilan17
I can confirm that this edit doesn't change the original meaning of 2 01 000. Thanks, Marijana
