### ISSUE TITLE
Comments received on DRAFT AMENDMENTS TO THE MANUAL ON CODES, VOLUME I.2 (WMO-NO. 306) BY FAST-TRACK PROCEDURE 

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/BUFR4#49]
# Summary and purpose
_DRAFT AMENDMENTS TO THE MANUAL ON CODES, VOLUME I.2 (WMO-NO. 306) BY FAST-TRACK PROCEDURE_ has been sent out on 28 July, 2020.

The focal points for codes and data representation matters are invited to review and comment by 29 September, 2020.

There are 11 proposals in _Part B - Binary Codes: FM 94 BUFR_, from No.13 to No.23.

# Action proposed
Comments received will be recorded here.

# Document
[FT-2020-2-Vol I.2.pdf](https://github.com/wmo-im/BUFR4/files/4993643/FT-2020-2-Vol.I.2.pdf)

[FT-2020-2-Vol I.2-Update.pdf](https://github.com/wmo-im/BUFR4/files/5007475/FT-2020-2-Vol.I.2-Update.pdf)

**Comment by chenxiaoxia2019** [comment]
Date:    28/07/2020 
Author: Jeff Ator: 
Comment: The new Table D sequence 3-12-035 (for Scatterometer level 2a data) is missing from the PDF document  even though it's included in the original proposal and in the branch https://github.com/wmo-im/BUFR4/blob/issue-20/BUFR_TableD_en_12.csv  Could you please correct this, to ensure that the new 3-12-035 sequence gets included in the November Table D update?
Action: To be updated.

**Comment by chenxiaoxia2019** [comment]
**No:** 2
**Date**: 31/07/2020
**Author**: Jeff Ator
**Comment**:  1). In the FT-2020-2-Vol I.2-Update.pdf document, there are 5 additional descriptors (0-01-007, 0-01-031, 0-02-048, 2-02-124, 0-02-026) shown at the end of the sequence and which should not be there.
2). In the ft-2020-2-new branch, 3-12-035 is now listed before 3-12-034 within the BUFR_TableD_en_12.csv file.

**Comment by amilan17** [comment]
All amendments have been approved by FT-2020-2.
