### ISSUE TITLE
apparent paradox in BNF attachment for FM-94 BUFR in WMO 306 manual

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/BUFR4#56]

**Comment by jbathegit** [comment]
One of my eagle-eyed colleagues spotted something interesting in the attachment to the manual for the BNF (Backus-Naur Form) for FM-94 BUFR, as shown below.  Apparently there's a Note (3) which says that each `<table b entry>` shall be represented using 95 characters; however, if you add up the lengths of all of the components included in the definition of `<table b entry>`, you get a total of 112 characters! 

![bufr_95_chars](https://user-images.githubusercontent.com/62722702/104743654-f029c400-5719-11eb-9b9e-bf0379847ce4.png)

**Comment by jbathegit** [comment]
BTW, and re: Note (1), this is another place in the manual which explicitly states that all characters in the units (i.e. `<UNITS_NAME>`) and meaning (i.e. `<ELEMENT NAME LINE 1>` and `<ELEMENT NAME LINE 2>`) for any Table B element are restricted to the CCITT IA5 character set, as we've been discussing in #55

**Comment by SimonElliottEUM** [comment]
@jbathegit the size of <UNITS NAME> is ambiguously defined in any case. It is either 24 characters (giving the the 112 total your colleague spotted) or smaller if one of the prescribed options is used. I note with a wry grin, that if <UNITS NAME> is "NUMERIC", then the table B entry will be represented using 95 characters as per note 3.

**Comment by amilan17** [comment]
@efucile -- do you see any impact on removing note 3 from the manual?

**Comment by amilan17** [comment]
No one is aware of this breaking anything....

**Comment by efucile** [comment]
> @efucile -- do you see any impact on removing note 3 from the manual?

I don't think it is breaking anything, but I also think that these exchange forms were replaced by the machine-readable tables in XML and CSV. Not sure if it is worth deleting the note. I would suggest deleting all chapter 3!

**Comment by amilan17** [comment]
decision: remove this entire section.

**Comment by jitsukoh** [comment]
@amilan17 this will be reflected in the next PDF publication. I move this to "validated" status.
