### ISSUE TITLE
update tables with editorial changes

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#58]
# Summary and purpose

Fix editorial inconsistencies in FT-2020-2 amendments found by copyeditor after codes were released.

**Comment by amilan17** [comment]
Table D Category 12

72b1b83

**Comment by amilan17** [comment]
Table D Category 15

d808068

**Comment by amilan17** [comment]
Table D Category 16

37055a7

**Comment by amilan17** [comment]
ffa571c

Table D Category 40

**Comment by amilan17** [comment]
4dbea5e

Code Table 0 02 006

**Comment by amilan17** [comment]
0660222#diff-aa5ba7025f89564d3f96e052eba6ec570b6170c25aa97b6330cd7dacdd8859ac

Code Table 0 33 055

**Comment by chenxiaoxia2019** [comment]
@amilan17  [81969b0](https://github.com/wmo-im/BUFR4/commit/81969b0860e76e6dc56ba71e3c9b84749d7014ee) has already been merged in Ft21 1 validation. (Line 329 and 337 in BUFRCREX_CodeFlag_en_33.csv) No changes showing in the Ft21 1 validation. FYI.
#60
> Needs verification
> 
> [0660222](https://github.com/wmo-im/BUFR4/commit/06602228680bc29ca35ca5137c47a8592c21a735)
> 
> [81969b0](https://github.com/wmo-im/BUFR4/commit/81969b0860e76e6dc56ba71e3c9b84749d7014ee)
> 
> Code Table 0 33

**Comment by amilan17** [comment]
odd. but I verified that the changes are there.
