### ISSUE TITLE
Validate Machine Readable Codes - v36 Release Candidate

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#61]
# Release Candidate 
https://github.com/wmo-im/BUFR4/releases/tag/v36RC

# Summary and purpose

To ensure that the v36RC machine-readable codes are valid and ready for testing during the comment period. 

# Action proposed

1.   [x]  Update script to NOT output the "\<No> " tag in the XML (see Issue #23)
1.   [x]  Identify key individuals to test
1.   [x]  Confirm file validation

# Discussions

# Machine-Readable Files

*   [ ] BUFR\_TableA\_en.txt
*   [ ] BUFR\_TableC\_en.txt
*   [ ] BUFR\_TableD\_en.txt
*   [ ] BUFRCREX\_CodeFlag\_en.txt
*   [ ] BUFRCREX\_TableB\_en.txt
*   [ ] CREX\_TableA\_en.txt
*   [ ] CREX\_TableC\_en.txt
*   [ ] CREX\_TableD\_en.txt
*   [ ] BUFR\_TableA\_en.xml
*   [ ] BUFR\_TableC\_en.xml
*   [ ] BUFR\_TableD\_en.xml
*   [ ] BUFRCREX\_CodeFlag\_en.xml
*   [ ] BUFRCREX\_TableB\_en.xml
*   [ ] CREX\_TableA\_en.xml
*   [ ] CREX\_TableC\_en.xml
*   [ ] CREX\_TableD\_en.xml

**Comment by amilan17** [comment]
removed \<No> tags -- ready to test.

**Comment by amilan17** [comment]
@SimonElliottEUM @erget tested and found no problems.

**Comment by SibylleK** [comment]
I have checked the XML-files They are OK, except of one or more space characters at the end of some entries. But these spaces could also be found in the csv-files.
A space at the end of the header of BUFRCREX_CodeFlag_en_01.csv leads to a "<Status->"-tag in BUFRCREX_CodeFlag_en.xml, as a space in the header is replaces by "-" in csv2xml.py.
To avoid unneeded spaces in the converted XML-files csv2xml.py could be supplemented by "field = field.rstrip()" and "header[i] = header[i].rstrip()".

**Comment by amilan17** [comment]
validated (extra space >> - is removed)
