### ISSUE TITLE
BUFRCREX Table B 15: Proposal for new BUFR descriptor extended integrated mass density

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#63]
# Branch

https://github.com/wmo-im/BUFR4/tree/issue63
# Summary and purpose

ECMWF is proposing a new BUFR descriptor for encoding integrated mass density data for SO2,  NO2  and HCHO.

# Stakeholders

Marijana Crepulja, Roberto Ribas, Antje Inness (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

The SO2 data from Sentinel5p as well as NO2  and HCHO contain negative values. These negative values cannot be handled by the current BUFR template and are discarded. This leads to a positive bias in the observations. Therefore the new BUFR descriptor is needed.

# Detailed proposal

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | -- 
0-15-022 | Extended Integrated mass density | kg m-2| 1 | -100000000 | 31| | |

**Comment by marijanacrepulja** [comment]
Comment related to our discussion re data width limit of 31 bits.  
To be able to encode negative values we need to set reference value to -10000000000 as proposed. If we set width to 31 bits we would not be able to encode positive data values, therefore width of 35 bits is needed,

**Comment by DavidBerryNOC** [comment]
If I've understood correctly the total mass of the atmosphere is ~ 10,000 kg/m2. Is the scale factor correct?

**Comment by SimonElliottEUM** [comment]
I would be interested to know the source variables from which this parameter is to be derived. I am struggling with the idea  of an instrument capable of leading to a measurement with an accuracy of 1 part in 1000000000. If the incoming data from S5p are in netCDF / HDF, then the variable would be type NC_DOUBLE.

**Comment by jbathegit** [comment]
Another potential issue, at least if we're still concerned about being able to represent Table B elements using Class 0:

A reference value of -10000000000 cannot be represented using descriptors 0-00-018 and 0-00-019.  The sign can be stored using 0-00-018, but the magnitude of this reference value cannot be stored in 0-00-019, which only has 80 bits and therefore room for only 10 characters.

**Comment by marijanacrepulja** [comment]
Thank you for all comments, we re considered our proposal and  took you comments on board. The proposal is updated as below. 



0-15-022 | Extended Integrated mass density | kg m-2 | 1 | -100000000 | 31
-- | -- | -- | -- | -- | --

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
