### ISSUE TITLE
CodeFlag 08: New code for Volcanic sulphur dioxide 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#64]
# Branch

https://github.com/wmo-im/BUFR4/tree/issue64
# Summary and purpose

ECMWF is proposing a new value in Code/Flag table 0-08-043 Atmospheric chemical or physical constituent type to enable encoding VOLCANIC SULPHUR DIOXIDE.

# Stakeholders

Marijana Crepulja, Roberto Ribas, Antje Inness (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

The new code value for VOLCANIC SULPHUR DIOXIDE in Code/Flag  for Atmospheric chemical or physical constituent type is needed to aid encoding and handling of the SO2 observation. 

# Detailed proposal

**CODE TABLE 0-08-043
0-08-043 Atmospheric chemical or physical constituent type**

Code Figure |  
-- | --
9 | VOLCANIC SULPHUR DIOXIDE

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 I confirm that proposal is finalized and branch is updated, and move this issue to "Validated" status.
