### ISSUE TITLE
Table B 02 and new BUFR sequence for representation of ground based lidar observations

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#65]
# Branch

https://github.com/wmo-im/BUFR4/tree/issue65
# Summary and purpose

ECMWF is proposing a new BUFR template for representation of ground based lidar observations. 

# Authors

Marijana Crepulja, Julie Letertre-Danczak, Angela Benedetti, Roberto Ribas (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for monitoring and operational assimilation of aerosol observations from  ground based lidar. Therefore a new BUFR template is needed.

# Detailed proposal

**1. Add a new entries in code table 0 08 043 Atmospheric chemical or physical constituent type**

Discussion: There is a need to distinguish between aerosol, cloud and aerosol/cloud measurement as it can be presented in particle backscatter. Code for aerosol already exists.

Proposal:
CODE TABLE 0-08-043
0-08-043   Atmospheric chemical or physical constituent type

Code Figure |  Retrieval identifier
-- | --
32 | Cloud
33 | Cloud and aerosols

**2. Add a new entry in the instrumentation class of  table B  (0-02-090)**  

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-02-090 | Instrument wavelength | m | 9 | 0 | 16

**3. Add a new BUFR template for ground based Lidar observations**

Table 			reference | Table 			references | Element 			name | Description 			/ comments
-- | -- | -- | --
3-09-027 |   | Multi wavelength ground based lidar observations |
||3 01 132 | Common Header Sequence
||0 08 043 | Atmospheric chemical or physical constituent type
||0 25 061 | Software Version Number  
||3 02 004 | General Cloud Information
||3 02 005 | Cloud Layer
||0 08 092| Measurement uncertainty expression| Note 18
||0 08 093 | Measurement Uncertainty Significance| see Note 15
||0 08 021 | Time Significance| =2 Time average
|| 0 04 025| Time period or displacement| see Note 13
||1 18 000 | Delayed replication of 18 descriptors
||0 31 001 | Delayed replication factor
||0 02 090 | Instrument wavelength
||1 15 000 | Delayed replication of 15 descriptors
||0 31 002 | Extended delayed replication factor
||0 07 007 | Height | see Note 15
||3 01 021| Latitude/longitude (high accuracy) | =2 Time average 
||0 15 073 | Attenuated   backscatter
||0 15 064 | Uncertainty   in attenuated backscatter
||0 15 074 | Particle backscatter coefficient  
||0 15 066 | Uncertainty in particle backscatter coefficient
||0 15 075 | Particle   extinction coefficient
||0 15 068 | Uncertainty   in particle extinction coefficient
||0 15 076 | Particle lidar Ratio
||0 15 077 | Uncertainty  in lidar ratio
||0 15 078 | Particle Depolarization Ratio
||0 15 072 | Uncertainty in depolarization ratio
||0 33 002 | Quality Information| Note 19
||0 10 071 | Vertical Resolution 
||0 27 079 | Horizontal Width of sampled volume

**Comment by amilan17** [comment]
@sergioh-pessoal @richardweedon help validate

**Comment by amilan17** [comment]
per discussion at meeting: spelling of wavelength will be corrected, reviewed by EUMETNET, in validation, branch will be created, sample will be provided and validated by Met Office

**Comment by marijanacrepulja** [comment]
There was a meeting between EUMETNET, Met Office and ECMWF. We agreed to update the sequence to be align with single wavelength Lidar BUFR sequence.

**Comment by marijanacrepulja** [comment]
[lidar_new_template_3wavelength.txt.gz](https://github.com/wmo-im/BUFR4/files/6516522/lidar_new_template_3wavelength.txt.gz)
[lidar_new_template_3wavelength.bufr.gz](https://github.com/wmo-im/BUFR4/files/6516523/lidar_new_template_3wavelength.bufr.gz)
[lidar_new_template.txt.gz](https://github.com/wmo-im/BUFR4/files/6516524/lidar_new_template.txt.gz)
[lidar_new_template.bufr.gz](https://github.com/wmo-im/BUFR4/files/6516525/lidar_new_template.bufr.gz)

**Comment by richardweedon** [comment]
Decode of test data run using ECCODES. 
[decode_UK_lidar_new.txt](https://github.com/wmo-im/BUFR4/files/6708182/decode_UK_lidar_new.txt)

**Comment by jitsukoh** [comment]
@amilan17 @marijanacrepulja I confirm that the proposal was finalized, branch is updated and validation is completed. I move this to validated status.
