### ISSUE TITLE
CodeFlag 01 and Table B 01: New BUFR descriptor and code table for Retrieval identifier 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#66]
# Branch

https://github.com/wmo-im/BUFR4/tree/issue66
# Summary and purpose

ECMWF is proposing new BUFR descriptor for Retrieval identifier and related code table.

# Authors

Marijana Crepulja (ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for assimilation of lidar observations from satellite. In order to identify different retrievals we need a new  descriptor and code table to define it.
 
# Detailed proposal

**1. Add a new entry in the identification class of  table B  (0-01-155)  and a new code table to describe the retrial**

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-01-155 | Retrieval identifier | Code 			table | 0 | 0 | 8

2. Add new CODE TABLE 0-01-155 for Retrieval identifier

Code Figure |  Retrieval identifier
-- | --
0 |  Standard  Correct  Algorithm
1-254| Reserved
255| Missing

**Comment by amilan17** [comment]
per meeting discussion: Abbreviation will be spelled out, data width will be changed, in validation, branch will be created

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.

**Comment by amilan17** [comment]
@jitsukoh @marijanacrepulja is "Standard Correct Algorithm" a proper noun?
