### ISSUE TITLE
Ambiguity in code table entries for 0-20-063

### ISSUE THREAD

**Issue by SimonElliottEUM** [wmo-im/BUFR4#68]
# Branch

[https://github.com/wmo-im/BUFR4/tree/issue68](https://github.com/wmo-im/BUFR4/tree/issue68)

# Proposal

Change definitions of entries 36 and 38 in code table 0-20-063.

36 - Convergence of CH clouds at a point above 45° forming or increasing and associated with a tropical disturbance  
38 - Convergence of CH clouds at a point above 45° dissolving or diminishing and associated with a tropical disturbance

# original issue text

Code table entries 36 and 38 in code table 0-20-063 are identical

**Comment by SibylleK** [comment]
The entries 31-39 of code table 0-20-063 have their origin in code table 0522 - Cc "Coloration and/or convergence of clouds associated with a tropical disturbance" of Volume I.1.
Therefore in entry 36 "forming or increasing" and in entry 38 "dissolving or diminishing" is missing.
It should be 
36 - Convergence of CH clouds at a point above 45° forming or increasing and associated with a tropical disturbance
38 - Convergence of CH clouds at a point above 45° dissolving or diminishing and associated with a tropical disturbance

**Comment by amilan17** [comment]
@jitsukoh @SimonElliottEUM -- This looks like a simple fix and I think we have time to include in FT2021-2. What do you think?

**Comment by SimonElliottEUM** [comment]
@jitsukoh @amilan17 Including this (purely typographical) fix in FT2021-2 would be fine with me

**Comment by jitsukoh** [comment]
I agree to include this in FT2021-2. Moved to in validation. @amilan17 can you create a branch and update? I move this issue to in validation status.

**Comment by SimonElliottEUM** [comment]
@amilan17 @jitsukoh I have updated the branch to reflect the input from @SibylleK

**Comment by jitsukoh** [comment]
@SimonElliottEUM thank you for updating the branch. @amilan17 I confirm that this proposal is finalized and branch is updated, and I move this issue to "Validated" status.
