### ISSUE TITLE
Normalize BUFR4 notes

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#74]
# Branch

[https://github.com/wmo-im/BUFR4/tree/notes](https://github.com/wmo-im/BUFR4/tree/notes)

https://github.com/wmo-im/BUFR4/compare/5e5caadb7ba8e2d98306dc0b527633694483e0d5...notes

# Purpose

To normalize all notes in published PDF and in GitHub repositories.

**Comment by amilan17** [comment]
*   migrate all existing notes in tables to a notes.csv file
*   Determine how to normalize notes denoted by a stars and numbers
*   add noteID column to CSVs

**Comment by amilan17** [comment]
BUFRCREX_CodeFlag_notes
* discuss: replace starred acronyms with full text + acronym, instead of using note

**Comment by amilan17** [comment]
BUFR_and_CREX_TableC_notes

BUFR_and_CREX_TableD_notes
* Many CREX tables in GitHub look like a copy of the BUFR tables and they differ from the manual.

**Comment by amilan17** [comment]
Moving this "column header" to note under the table. Is there a better way to phrase this? 

noteID| note | table
5 | (0 is good, 1 is bad) | 025112, 025113
-- | -- | --


</body></html>

**Comment by amilan17** [comment]
Should we develop the codes for this? 

_0 02 012
Radiosonde computational method
(To be developed)_

**Comment by amilan17** [comment]
improve note phrasing in table 0 02 022

22 | Bit flags denoting the elements included in processing sounding data.
-- | --

**Comment by amilan17** [comment]
@SimonElliottEUM @richardweedon Will you have time to look at this soon? I'd like to finalize this for FT.

**Comment by SimonElliottEUM** [comment]
@amilan17 @richardweedon The updated not to 0-02-022 looks fine to me. It can be used like that for that for this FT

**Comment by amilan17** [comment]
unresolved questions moved to specific issues
