### ISSUE TITLE
Formatting error in BUFR Tables 35

### ISSUE THREAD

**Issue by erget** [wmo-im/BUFR4#75]
The BUFR tables found [on the WMO website](https://community.wmo.int/activity-areas/wmo-codes/manual-codes/previous-versions), [v35](https://community.wmo.int/activity-areas/wmo-codes/manual-codes/previous-versions/2020-11-16), have in the XML code/flag tables tags like this:

`<Status->Operational</Status->`

The `-` invalidates the tag and makes the XML invalid. Can this be fixed?

**Comment by amilan17** [comment]
@erget -- this is fixed in v36 [https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version.](https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version.)

**Comment by erget** [comment]
Any plans to fix it in the existing tables? Some applications require a specific table version.

**Comment by amilan17** [comment]
There is no plan to update version 35.

**Comment by amilan17** [comment]
@erget -- I think I fixed it, can you check the formatting in v35.1 pre-release? 

https://github.com/wmo-im/BUFR4/releases/tag/v35.1

**Comment by erget** [comment]
@amilan17 looks like that solved it - we did a basic comparison to confirm that only `<Status>` had changed - ✔ - and then used `xmllint` to confirm correctness of the tables. All is well, and the [Vocabulary Manager](https://vocabulary-manager.eumetsat.int/), the system we use at EUMETSAT for managing i.a. WMO tables, processes them just fine. Many thanks!
