### ISSUE TITLE
CodeFlag table missing EntryName value for 031031 element

### ISSUE THREAD

**Issue by TheRed86** [wmo-im/BUFR4#76]
Hi,

I would like to know where I can find the standard to define fields in CodeFlag tables (i.e. FXY,ElementName_en,CodeFigure,EntryName_en,EntryName_sub1_en,EntryName_sub2_en,Note_en,Status). Which of them are mandatory, which optional?

My question arises from an issue had reading code/flag tables: for the element **031031** the **EntryName_en** content is moved to **EntryName_sub1_en**. This is the unique element not having EntryName_en defined: 

```
  <BUFRCREX_CodeFlag_en>
    <No>4433</No>
    <FXY>031031</FXY>
    <ElementName_en>Data present indicator</ElementName_en>
    <CodeFigure>1</CodeFigure>
    <EntryName_sub1_en>0 = Data present, 1 = Data not present</EntryName_sub1_en>
    <Status>Operational</Status>
  </BUFRCREX_CodeFlag_en>
```

All other elements are defined as the following example:
```
  <BUFRCREX_CodeFlag_en>
    <No>4434</No>
    <FXY>033002</FXY>
    <ElementName_en>Quality information</ElementName_en>
    <CodeFigure>0</CodeFigure>
    <EntryName_en>Data not suspect</EntryName_en>
    <Status>Operational</Status>
  </BUFRCREX_CodeFlag_en>
```

Is there a particular reason for that? Should **EntryName_en** be a mandatory field always having a value? Where can I find info on the standard to fill tables?

I really appreciate any help you can provide.

**Comment by amilan17** [comment]
@TheRed86 -- I think you found an error that we need to fix. The XML is generated from the working CSV files, but the published [Manual on Codes (WMO No.- 306), volume I.2](https://library.wmo.int/index.php?lvl=notice_display&id=10684#.X18yfpMza3I) is the authoritative reference and this is a snapshot of the same table in the manual. 

![](https://user-images.githubusercontent.com/5168866/122229737-4c576680-ceb9-11eb-8e43-ba18bf9a6035.png)

**Comment by amilan17** [comment]
Either the entry name needs to be added OR we need to fix the code that generates the XML to not omit expected xml tags.

**Comment by TheRed86** [comment]
Many thanks, @amilan17. Your answer has been very useful for me. 
Looking forward to the fix.

Regards

**Comment by amilan17** [comment]
this will be addresses as needed in this issue: #80
