### ISSUE TITLE
Proposal for BUFRCREX_CodeFlag_en_40.csv

### ISSUE THREAD

**Issue by erget** [wmo-im/BUFR4#78]
# Branch

https://github.com/wmo-im/BUFR4/tree/issue78

# Summary and purpose

This proposal adds a new ocean product quality flag table for use with HY-2B BUFR products.

# Stakeholders

Users of HY-2B BUFR products.

# Action proposed

Adopt the changes in the referenced pull request.

# Discussions

EUMETSAT disseminates HY-2B radiometer products in BUFR format. Currently, a local code table is used in order to provide quality information. This proposal would encode the same information using a flag table. It is proposed to use a WMO descriptor rather than a local one in order to maximise compatibility.

@SimonElliottEUM as discussed.

# Detailed proposal

### Table B 40
<table><tbody><tr><td><strong>ClassNo</strong></td><td><strong>ClassName_en</strong></td><td><strong>FXY</strong></td><td><strong>ElementName_en</strong></td><td><strong>BUFR_Unit</strong></td><td><strong>BUFR_Scale</strong></td><td><strong>BUFR_ReferenceValue</strong></td><td><strong>BUFR_DataWidth_Bits</strong></td><td><strong>CREX_Unit</strong></td><td><strong>CREX_Scale</strong></td><td><strong>CREX_DataWidth_Char</strong></td></tr><tr><td><strong>40</strong></td><td>Satellite data</td><td>40077</td><td>Ocean product quality flag</td><td>Flag table</td><td>0</td><td>0</td><td>8</td><td>Flag table</td><td>0</td><td>3</td></tr></tbody></table>

### Code Flag 40

| **FXY** | ElementName\_en | CodeFigure | EntryName\_en |
| --- | --- | --- | --- |
| **40077** | Ocean product quality flag | 1 | Sea surface temperature not OK |
| **40077** | Ocean product quality flag | 2 | Sea surface wind speed not OK |
| **40077** | Ocean product quality flag | 3 | Atmospheric water vapour content not OK |
| **40077** | Ocean product quality flag | 4 | Cloud liquid water content not OK |
| **40077** | Ocean product quality flag | 5-7 | Reserved |
| **40077** | Ocean product quality flag | All 8 | Missing value |

**Comment by amilan17** [comment]
@jitsukoh -- i just discovered this issue. Is it too late to include in FT2021-2? 

this PR shows the proposal: https://github.com/wmo-im/BUFR4/pull/77/files

**Comment by jitsukoh** [comment]
@amilan17 I think it is better to have a review process by the CGMS group.
@SimonElliottEUM would you be able to ask the group to review this proposal?

**Comment by SimonElliottEUM** [comment]
@amilan17 @jitsukoh I prefer to leave this for next time rather than rush at it now.

**Comment by jitsukoh** [comment]
@SimonElliottEUM noted! Do you mind taking over this issue from Daniel? It was my fault to skip this in this cycle, but it is generally difficult to follow up issues owned by non-TT-members...

**Comment by SimonElliottEUM** [comment]
@jitsukoh @amilan17 I am happy to follow this up. As of today (01/12/2021), I start a new role at EUMETSAT and have moved to the same Department and Division as Daniel (again). I will continue to support WMO as before - no change needed, but it will be a little easier for Daniel and I to work together again from today.

**Comment by amilan17** [comment]
@SimonElliottEUM @erget I think Table B needs CREX values?

**Comment by SimonElliottEUM** [comment]
@erget @amilan17  I am 100% super certain that there will never be data using the CREX version but indeed we should define it anyway. As it is a standard 8-bit wide flag table in BUFR it should just say UNIT Flag table, SCALE 0, DATA WIDTH (Characters) 3 for the CREX columns

**Comment by amilan17** [comment]
> @amilan17 I think it is better to have a review process by the CGMS group. @SimonElliottEUM would you be able to ask the group to review this proposal?

@SimonElliottEUM were you able to discuss with CGMS group?

**Comment by jitsukoh** [comment]
@amilan17 @SimonElliottEUM cannot attend next week's meeting and we've agreed that this will be delayed to the next cycle.

**Comment by SimonElliottEUM** [comment]
@amilan17 @jitsukoh Due to the evolving pandemic situation, my trip to Sodankylä next week has been postponed. I may well be able to attend the meeting. In any case the CGMS task group will not be able to discuss this until early next year, so delaying until the next cycle is best.

**Comment by jitsukoh** [comment]
@SimonElliottEUM that's a pity... but probably a good news for TT-TDCF :) this issue will be discussed in the next cycle. See you next week.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-16.3.2022:](https://github.com/wmo-im/CCT/wiki/Teleconference-16.3.2022:) to be discussed during meeting in April

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

still in process, move to next FT

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022) notes: 

still in progress

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
@antoinemerle and @SimonElliottEUM will update the branch

**Comment by antoinemerle** [comment]
Hi @amilan17 ,

the code `FXY` : `40075` is already taken by `Retrieval error covariance matrix for humidity in principal component domain`

![image](https://github.com/wmo-im/BUFR4/assets/10506061/adc38bad-6d73-4266-a151-20da335112a0)


I proposed to take `040077` is this okay for you @amilan17 ?
If this is okay, I will commit the changes to the branch.

So the proposition will be then



# NEW

<table><tbody><tr><td><strong>ClassNo</strong></td><td><strong>ClassName_en</strong></td><td><strong>FXY</strong></td><td><strong>ElementName_en</strong></td><td><strong>BUFR_Unit</strong></td><td><strong>BUFR_Scale</strong></td><td><strong>BUFR_ReferenceValue</strong></td><td><strong>BUFR_DataWidth_Bits</strong></td><td><strong>CREX_Unit</strong></td><td><strong>CREX_Scale</strong></td><td><strong>CREX_DataWidth_Char</strong></td></tr><tr><td><strong>40</strong></td><td>Satellite data</td><td>40077</td><td>Ocean product quality flag</td><td>Flag table</td><td>0</td><td>0</td><td>8</td><td>Flag table</td><td>0</td><td>3</td></tr></tbody></table>

### Code Flag 40

| **FXY** | ElementName\_en | CodeFigure | EntryName\_en |
| --- | --- | --- | --- |
| **40077** | Ocean product quality flag | 1 | Sea surface temperature not OK |
| **40077** | Ocean product quality flag | 2 | Sea surface wind speed not OK |
| **40077** | Ocean product quality flag | 3 | Atmospheric water vapour content not OK |
| **40077** | Ocean product quality flag | 4 | Cloud liquid water content not OK |
| **40077** | Ocean product quality flag | 5-7 | Reserved |
| **40077** | Ocean product quality flag | All 8 | Missing value |

**Comment by amilan17** [comment]
yes, that works.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023) notes:

Antoine will update the branch

**Comment by antoinemerle** [comment]
Dear @amilan17 ,

the branch has been updated by the two following commit :
- the code flag table 40 : https://github.com/wmo-im/BUFR4/commit/8af682d9a9d03d6b10f84f06547ad53f1a372001
- the table B 40 : https://github.com/wmo-im/BUFR4/commit/29d10d4bab8bb7c298851356db308a051fdce481

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.15.December.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.15.December.2023) notes: 

@amilan17 check the branch
