### ISSUE TITLE
New data category Lidar (ground based) in BUFR Table A

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#79]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue79

# Summary and purpose

 ECMWF proposes new entry to BUFR table A for the purpose of representing a Lidar ground based observations.

# Authors

Marijana Crepulja (ECMWF)

# Action proposed

The meeting is kindly asked to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for monitoring and assimilation of ground based lidar data. To aid better identification of the data new data category is needed.

# Detailed proposal

Add the new code 32 Lidar (Ground based) in the BUFR table A

CodeFigure | Meaning_en | Status
-- | -- | --

32 | Lidar (Ground based) | Operational
-- | -- | --

**Comment by marijanacrepulja** [comment]
Hi @amilan17, could you please create the branch for the issue. Thanks, Marijana

**Comment by amilan17** [comment]
done.

**Comment by marijanacrepulja** [comment]
Hello @jitsukoh, I have updated the issue79 branch. 

This is related to https://github.com/wmo-im/CCT/issues/53.

**Comment by jitsukoh** [comment]
@marijanacrepulja thank you for updating the branch.
@amilan17 I cannot see the "compare" button in the branch... Is there any way to see what changes are made in the branch?

**Comment by amilan17** [comment]
https://github.com/wmo-im/BUFR4/compare/master...issue79

**Comment by jitsukoh** [comment]
@amilan17 thank you for the difference. Sorry I touched "close issue" button by mistake, but is this issue still open?? 
@marijanacrepulja I confirm that proposal is finalized and branch is updated, and move this issue to "Validated" status.
