### ISSUE TITLE
Code Table 0 01 036

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#83]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue83
# Summary and purpose
We are presently in the process of coding up BUFR 3-15-007 for distributing ship-based CTD data, which we presently issue in TESAC.

Could I ask for the following changes to be made to the code table for descriptor 0 01 036 (Agency in charge of operating the observing platform) at the earliest opportunity.

1. rename 826002  United Kingdom, Southampton Oceanography Centre (SOC) to United Kingdom, National Oceanography Centre (NOC) (SOC no longer exists as it has become the NOC)
2. and to add (agencies who are all vessel operators)
- 826003 United Kingdom, Centre for Environment, Fisheries and Aquaculture Science (Cefas)
- 826004 United Kingdom, Marine Scotland (MS)
- 826005 United Kingdom, Plymouth Marine Laboratory (PML).
- 826006 British Antarctic Survey (BAS)

# Stakeholders
Met Office UK

# Discussions

# Detailed proposal

826002 | United Kingdom, ~Southampton~ National Oceanography Centre ~(SOC)~ (NOC)
826003 | United Kingdom, Centre for Environment, Fisheries and Aquaculture (Cefas)
826004 | United Kingdom, Marine Scotland (MS)
826005 | United Kingdom, Plymouth Marine Laboratory (PML)
826006 | United Kingdom, British Antarctic Survey (BAS)

**Comment by amilan17** [comment]
Are there best practices around re-naming agencies? 

In this case, the requester wrote: "...NOC (National Oceanography Centre) includes what was previously known as SOC (Southampton Oceanography Centre). I don’t believe  the ‘renaming’ would cause any confusion (as the UK CTD data exchanged so far have all been in TESAC and so have not included information on the ship’s operator)."

**Comment by amilan17** [comment]
per Jeff Ator -- doesn't think it's a problem

**Comment by amilan17** [comment]
@jitsukoh - branch is ready

**Comment by jitsukoh** [comment]
@amilan17 I confirm that the branch is updated and the issue was moved to the validated status.
