### ISSUE TITLE
BUFR4 table used also in GRIB2

### ISSUE THREAD

**Issue by manfredsc** [wmo-im/BUFR4#84]
satellite classification (BUFRCREX_CodeFlag_en_02.csv, FXY=02020) is also needed for GRIB2 decoding,
wouldn't it make sense to put it into CCT? It seems odd that GRIB2 decoding needs tables from BUFR4.

**Comment by amilan17** [comment]
@jitsukoh -- should the team discuss this suggestion?

**Comment by jitsukoh** [comment]
@wmo-im/tt-tdcf can anybody explain which GRIB2 template this issue refers to?

**Comment by manfredsc** [comment]
Sorry for the confusing description.
Code Table 0-02-020

**Comment by manfredsc** [comment]
I encountered it with the wgrib2 software.
It needs it to decode "spectral bands for satellite", product definition template 4.31 or 4.32.

See the notes in these templates:
Note: For “satellite series of band nb”, “satellite numbers of band nb” and “instrument types of band nb”, it is recommended to
encode the values as per BUFR Code tables 0 02 020, 0 01 007 (Common Code table C–5) and 0 02 019 (Common
Code table C–8), respectively.

**Comment by manfredsc** [comment]
As you see, the latter two tables are in CCT, but 0-02-020 is not.

**Comment by SimonElliottEUM** [comment]
Thanks @manfredsc for pointing this out. Your point is valid. I suspect that users of the satellite data in GRIB2 are generally using the satellite identifier (from CCT C-5) and so have no been worrying about the satellite classification

**Comment by manfredsc** [comment]
Well, wgrib2 decided to decode it, at some point, so it is difficult to rip it out again...
Actually it affects templates 4.30 to 4.35.
BTW: this "code table defined by originating/generating centre" is not really helpful. Most centres will
simply follow the recommendations, at which point this template (non-)definition becomes more or less moot.
It would be much more natural to have some baseline definitions and some range of code points "reserved for local use"
like everywhere else.

**Comment by sebvi** [comment]
The notes are clear: it is recommended to use the existing BUFR tables for consistency but it is not a requirement. In encodes, it is not enforced to use the BUFR tables.

It is a valid point made here but unfortunately I don't think we can change this retrospectively without breaking the usage of the templates: we don't know if someone somewhere decided to create their own tables using the same range than the BUFR tables with different meaning.

The only way would be to create new, separate templates where the usage of the BUFR tables is a requirement and discouraged the usage of the existing satellite templates. I personally think it is not worth the effort. But it could be reconsidered for GRIB3

**Comment by manfredsc** [comment]
OK, I agree.
As I said, I find the notion of "recommended" in the context of such standards not really helpful. In the end, there
are tools which have to decode this mess.
Should I open an issue against GRIB3, so this does not get lost?

**Comment by amilan17** [comment]
@manfredsc - I am closing this issue, but you may open a new issue in GRIB3 project: [https://github.com/wmo-im/GRIB3/issues](https://github.com/wmo-im/GRIB3/issues)

Also, please reference this one so we can refer to the initial request. Thanks.
