### ISSUE TITLE
Table B 14: New BUFR descriptor for the GIIRS observations

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#85]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue85
# Summary and purpose

ECMWF and UKMO are proposing a new BUFR descriptor for representation of GIIRS observations.

# Stakeholders

Chris Burrows (ECMWF), Nigel Atkinson (UKMO), Marijana Crepulja(ECMWF)

# Action

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

Geostationary Interferometric Infrared Sounder (GIIRS) provides high spectral resolution temperature and humidity information over China and surrounding regions (northern hemisphere only). The domain is scanned every two hours, thus providing the capability of a 4D-Var system to infer wind information by tracing water vapor structure. The new BUFR descriptor is proposed to aid use of the data in NWP.

We need a descriptor that relates to radiance noise, where the radiance is defined as descriptor 0-14-044 Channel radiance.

We propose a new descriptor 0-14-049 in class 14 with the same bit width and scale as 0-14-044. But no need for an offset as it is by definition positive.

# Detailed proposal

**1. Add a new entry in the Radiation and radiance class 14 of  table B  (0-14-049)**  

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-14-049| NOISE EQUIVALENT DELTA RADIANCE | W m-2 sr-1 cm|7|0|22|

**Comment by amilan17** [comment]
need to consult with CGMS and CMA
@SimonElliottEUM 
@Annie-FangZHAO

**Comment by marijanacrepulja** [comment]
I am sharing a comment from Chris Burrows my ECMWF colleague regarding involvement of CMA.

"We have been keeping CMA informed, in particular Qiang Guo (Chief Scientist & Designer of Ground Segment for Chinese GEO Microwave Satellite).  He seems satisfied with it. Other colleagues at CMA should have been aware through the ITWG meeting, and we did not get any feedback from those present."

**Comment by SimonElliottEUM** [comment]
We will pick this up at the CGMS meeting on 27/10/2021. (CMA will be represented by XU Zhe)

**Comment by Annie-FangZHAO** [comment]
@marijanacrepulja 
Dear Marijana,
After reporting to CMA headquarter and conducting extensive discussions with colleagues from the Observation Division and the Satellite Center, we appreciate ECMWF, UKMO of using FY-4 GIIRS products and making consideration of representing the products in BUFR, and have 2 comments as follows:
1.We support to add new entry 0-14-049 to Table B, the details has been checked by experts from the Satellite Center.
2.For FY-4 GIIRS observations, CMA as the originating/generating unit of the product, we’d like to cooperate with users such as ECMWF, UKMO and EUMETSAT to develop BUFR template in follow-up collaborations of global dissimination and services of the products. At this stage, is it possible to assimilate the data to NWP as a local BUFR sequence.
Thanks.

**Comment by SimonElliottEUM** [comment]
It is generally a preferable approach to have the encoding sequence conceived and proposed by the data producers. EUMETSAT will be happy to collaborate with @Annie-FangZHAO at CMA, along with UKMO and ECMWF on this.

**Comment by amilan17** [comment]
Decision: only add new entry for Table B in FT22-1, BUFR sequence will be proposed for FT22-2

**Comment by amilan17** [comment]
@marijanacrepulja I just created a branch. Do you still want this to go through FT22-1?

**Comment by amilan17** [comment]
@marijanacrepulja I just created a branch. Do you still want this to go through FT22-1?

**Comment by marijanacrepulja** [comment]
Hello @jitsukoh and @amilan17  I have now updated the issue85 branch with the above proposal.

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 I confirm that the branch is updated and the issue is moved to the validated status.
