### ISSUE TITLE
Table B 0 08 045 is missing

### ISSUE THREAD

**Issue by amilan17** [wmo-im/BUFR4#88]
# Branch

https://github.com/wmo-im/BUFR4/tree/issue83

# Summary and purpose

0 08 045 is missing. Referenced in Class 08, note 7: "When descriptor 0 08 043 is used to specify particulate matter (PM) under a given size threshold, descriptor 0 08 045 may also be used to further specify a subset of the PM population on the basis of ion composition."  
page: BUFR/CREX Table B/08 - 5

# Stakeholders

include as appropriate

# Action proposed

Add missing reference or update note

# Discussions

see comments below

# Detailed proposal

1.  Change note to: "When descriptor 0 08 043 is used to specify particulate matter (PM) under a given size threshold, descriptor **0 08 044 or 0 08 046** may also be used to further specify a subset of the PM population on the basis of ion composition."
~2.  Add title for table 0 08 44 in PDF~

**Comment by jbathegit** [comment]
0-08-044 apparently does exist, as "CAS registry number".  I just checked the BUFRCREX_vv_0_0_TableB_en.xml files for vv = 35, 36, and 37, and all of them include 0-08-044 as follows:

```
  <BUFRCREX_vv_0_0_TableB_en>
    <ClassNo>08</ClassNo>
    <ClassName_en>Significance qualifiers</ClassName_en>
    <FXY>008044</FXY>
    <ElementName_en>CAS registry number</ElementName_en>
    <BUFR_Unit>CCITT IA5</BUFR_Unit>
    <BUFR_Scale>0</BUFR_Scale>
    <BUFR_ReferenceValue>0</BUFR_ReferenceValue>
    <BUFR_DataWidth_Bits>88</BUFR_DataWidth_Bits>
    <CREX_Unit>Character</CREX_Unit>
    <CREX_Scale>0</CREX_Scale>
    <CREX_DataWidth_Char>11</CREX_DataWidth_Char>
    <Status>Operational</Status>
  </BUFRCREX_vv_0_0_TableB_en>
```

I presume it also exists in earlier versions as well, but at this point I only just checked 35, 36, and 37.

**Comment by SibylleK** [comment]
It seems, that 008045 has never been validated and was finally withdrawn? Information could be found in the report of the Joint Meeting of CT-MTDCF and ET-DRC in Montreal 2006. The proposed code table was:

Code table 0 08 045
Code figure	Meaning
0	Particulate Matter (all types)
1	 NO3(-)
2	 NH4(+)
3	 Na(+)
4	 Cl(-)
5	 Ca(2+)
6	 Mg(2+)
7	 K(+)
8	 SO4(2-)
9-200	reserved
201-254	reserved for local use
255	missing

But, at this time the Common Code Table C-14 does not exit and was developed only afterwards.

Therefore, the note should rather be changed in: 
"When descriptor 0 08 043 is used to specify particulate matter (PM) under a given size threshold, descriptor 0 08 044 or 0 08 046 may also be used to further specify a subset of the PM population on the basis of ion composition."

**Comment by amilan17** [comment]
@jbathegit  ok. I assume it's 0 08 044 is not in this CSV below, because we can't copy the entire CAS Registry. [https://github.com/wmo-im/BUFR4/blob/master/BUFRCREX_CodeFlag_en_08.csv](https://github.com/wmo-im/BUFR4/blob/master/BUFRCREX_CodeFlag_en_08.csv)

@jitsukoh I recommend publishing this table in the PDF in 

![](https://user-images.githubusercontent.com/5168866/141081972-9b7f633d-9721-496d-8440-a759958fa577.png)

**Comment by amilan17** [comment]
@SibylleK Thank you for finding this [2006 report](https://wmoomm.sharepoint.com/:b:/s/wmocpdb/Ea15z03lVuNOkAqHCPIoyfEBQyk3djuC2uP_diXo3H8Xrw?e=Xycmpg). I see that is was also "awaiting validation" in the [2007 report](https://wmoomm.sharepoint.com/:b:/s/wmocpdb/EXZ490Dijt1Om5GGaMJr8YMBq4HFi6vQO36ilZmKtv4M0g?e=BQbtTG) and then no mention of it in the 2008 reports.

**Comment by jbathegit** [comment]
This is interesting.  I thought the XML files were generated from the CSV files, so I'm curious how 008044 is in the former but not the latter?

I guess I would have been expecting something like we have for 008046 in the CSV files, where there's just a placeholder marking that the entry is occupied, but like you said not a copy of the entire CAS registry.  I agree that would be unnecessary and incredibly burdensome.

**Comment by amilan17** [comment]
https://github.com/wmo-im/GRIB2/blob/master/xml/CodeFlag.xml

**Comment by amilan17** [comment]
don't put reference to 0 08 044 in section with code tables, because it's not a code table

**Comment by amilan17** [comment]
> This is interesting. I thought the XML files were generated from the CSV files, so I'm curious how 008044 is in the former but not the latter?
> 
@jbathegit 0 08 044 is listed https://github.com/wmo-im/BUFR4/blob/master/BUFRCREX_TableB_en_08.csv and this is what the https://github.com/wmo-im/BUFR4/blob/master/xml/BUFRCREX_TableB_en.xml is generated from

**Comment by amilan17** [comment]
@jitsukoh the notes file in the branch is updated and ready for validation

**Comment by jitsukoh** [comment]
@amilan17 thank you for updating. Looks good. I move this issue to the validated status.
