### ISSUE TITLE
Proposal for BUFRCREX_TableB_en_15.csv, change reference value for 0 15 083

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/BUFR4#89]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue89

# Summary and purpose

Change the reference value for 0 15 083 - GNSS derived neutral atmosphere gradient to allow negative gradients.

# Stakeholders

# Action proposed

The team is kindly asked to review and approve the content for inclusion within the next update to the WMO Manual on Codes.

# Discussions

The descriptor for GNSS derived neutral atmosphere gradient was recently proposed by issue 18 “New Sequence and descriptors for GNSS Slant Total Delay BUFR” and operational since June 2021.
Only afterwards it has been recognized, that the gradient could be negative but the reference value is zero.
Therefore, it is proposed to change the reference value for descriptor 0 15 083 to be able to encode also negative GNSS derived neutral atmosphere gradients with the existing descriptor and sequence.

# Detailed proposal

Change RefVal of 015083.
|FXY|ElementName|Note|Unit|Scale|RefVal|DataWidth|CREX_Unit|CREX_Scale|CREX_Width|
|--|--|--|--|--|--|--|--|--|--|
|015083| GNSS derived neutral atmosphere gradient (see Note 17)|(17)…| m| 5| -8192| 14| m| 5| 9|

**Comment by amilan17** [comment]
@amilan17  Research changes between v13 and v14

**Comment by amilan17** [comment]
@jbathegit can do a diff

**Comment by amilan17** [comment]
@amilan17 create branch

**Comment by jbathegit** [comment]
Per our discussion, here are the changes to Table B descriptors that were made between v13 and v14, according to NCEP's records:

-  **0-14-001, 0-14-002, 0-14-003, 0-14-004, 0-14-011, 0-14-012, 0-14-013, and 0-14-014** each changed bit width from 12 to 17, and changed reference value from -2048 to -65536.
-  **0-14-017** changed scale factor from -3 to 0, changed bit width from 12 to 10, and changed reference value from -2048 to -512.
-  **0-14-018** changed scale factor from -3 to 0.
-  **0-14-028, 0-14-029, and 0-14-030** each changed bit width from 16 to 20.

**Comment by SibylleK** [comment]
Branch is updated. I also changed the title, as the reference value for 0 15 083 - "GNSS derived neutral atmosphere gradient" should be changed and not 0 08 083.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/BUFR4/compare/FT22-1...issue89](https://github.com/wmo-im/BUFR4/compare/FT22-1...issue89)

@jitsukoh I think this valid

**Comment by jitsukoh** [comment]
@amilan17 @SibylleK I confirm that the branch is updated and the issue is moved to the validated status.
