### ISSUE TITLE
New BUFR template for cloud radar observations and new descriptors table B class 21 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/BUFR4#90]
# Branch
https://github.com/wmo-im/BUFR4/tree/issue90

# Summary and purpose

ECMWF is proposing a new BUFR template for representation of radar observations from EarthCARE (Cloud, Aerosol and Radiation Explorer) 

# Stakeholders

Marijana Crepulja, Mark Fielding, Marta Janiskova (all from ECMWF)

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for monitoring and operational assimilation of cloud observations from EarthCARE . Therefore a new BUFR template is needed.

# Detailed proposal

**1. Add a new entries in the radar data class of table B** 

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0 21 007| Radar reflectivity factor | dB|2|-9000|15|
0 21 008| Uncertainty in radar reflectivity factor | dB|2|0|13|
0 21 009| Vertical Doppler velocity | m/s|2|-10000|15|
0 21 010| Uncertainty in Vertical Doppler velocity | m/s|2|-10000|15|

**2. Add a new entry in the Processing information class of  table B  (0-25-139)  and a new code table to describe the Processing level** 

F  X Y          | ELEMENT NAME        | UNIT | SCALE | REFERENCE 	VALUE | DATA 			WITH  (bits)
-- | -- | -- | -- | -- | --
0-25-139 | Processing level  | Code 			table | 0 | 0 | 5

**3. Add new CODE TABLE 0-25-139 for Processing level** 

Code Figure |  Processing level
-- | --
0 |  L1B
1 |  L2A
2-30| Reserved
31| Missing

**4. Add a new BUFR template for radar cloud observations**

Table 			reference | Table 			references | Element 			name | Description 			/ comments
-- | -- | -- | --
3-21-031 |   | Satellite Radar observations |
||0 01 007 | Satellite Identifier
||0 02 019 | Satellite Instruments
||0 01 033 | Identification of originating/generating centre
||0 01 034 | Identification of originating/generating sub-centre
||3 01 011| Year, Month, Day| 
||3 01 013 | Hour, Minute, Second| 
||3 01 021 | Latitude/longitude (high accuracy)| 
||0 10 033| Altitude (Platform To Ellipsoid)
|| 0 08 043| Atmospheric chemical or physical constituent type| 
||0 25 139| Processing level| 
||0 02 153| Satellite channel centre frequency
||1 06 000| Delayed replication of 6 elements
|| 0 31 002| Extended delayed descriptor replication factor
||0 07 071| Height (high resolution)
||0 21 007| Radar reflectivity factor
||0 21 008| Uncertainty in radar reflectivity factor
||0 21 009| Vertical Doppler velocity
||0 21 010| Uncertainty in vertical Doppler velocity
||0 33 003| Quality information

**Comment by marijanacrepulja** [comment]
[EarthCARE-CPR1B_test.bufr.gz](https://github.com/wmo-im/BUFR4/files/7512463/EarthCARE-CPR1B_test.bufr.gz)

**Comment by amilan17** [comment]
ready for validation

**Comment by amilan17** [comment]
@richardweedon @marianmajan-ibl @jbathegit validate with sample data

**Comment by amilan17** [comment]
@marijanacrepulja double check with colleagues on the request for dBZ

**Comment by marijanacrepulja** [comment]
We agree to use dB units for Radar reflectivity factor, after consulting with my colleagues.

**Comment by marijanacrepulja** [comment]
I have updated branch with new entries in B and D table. 
Sample data and corresponding output of decoded BUFR file is attached
[EarthCARE-CPR1B_test.zip](https://github.com/wmo-im/BUFR4/files/7644121/EarthCARE-CPR1B_test.zip)

@richardweedon @marianmajan-ibl @jbathegit could you please help with validation. 
Many thanks.

**Comment by jbathegit** [comment]
@marijanacrepulja I've started to work on this.  However, I don't see 0-25-139 defined anywhere in Table B.  Is this another new proposed new Table B descriptor?  If so, then could you please add it to part 1 of this proposal?

**Comment by jbathegit** [comment]
Thanks @marijanacrepulja.  With that, I was able to decode the BUFR from your zip bundle, and I spot-checked several reports and confirmed I got the same results as shown in your .txt file.  So from my standpoint it's a successful validation.

**Comment by amilan17** [comment]
@marijanacrepulja I updated the branch to include the "Element Description" as indicated above in Table D. I also changed several words to begin with lower case, because they are not proper nouns. If you agree with these edits, please tag Jitsiku for final approval.

**Comment by amilan17** [comment]
https://github.com/wmo-im/BUFR4/compare/FT22-1...issue90

**Comment by richardweedon** [comment]
Managed to decode the sample data. In addition received a positive review from our satellite applications scientists. From my perspective the review is complete.

**Comment by marianmajan-ibl** [comment]
Hello, @marijanacrepulja, I have successfully decoded your samples with the tables from the branch. However, currently the converted file is nearly 4 GB, I have added to the GDrive again -- https://drive.google.com/file/d/1zsEZg9Fl6rNDEL5Br16kUYfMuLX-LGGr/view?usp=sharing

Very quick manual check showed the same results with one exception -- it seems that we have an error when showing `0 02 153 Satellite channel centre frequency =  [Hz]` -- the value is empty. I will try to investigate this (but I assume it is problem of our decoding / showing results).

**Comment by marijanacrepulja** [comment]
@jbathegit, @richardweedon, @marianmajan-ibl Thanks very much for your help to validate this proposal!

**Comment by marijanacrepulja** [comment]
> @marijanacrepulja I updated the branch to include the "Element Description" as indicated above in Table D. I also changed several words to begin with lower case, because they are not proper nouns. If you agree with these edits, please tag Jitsiku for final approval.

@amilan17 Many thanks for updating the branch. I agree with the modifications you've made. I removed only  "L1B, L2A" from "Element Description" in the branch and the proposal, because it is only relevant to this proposal.

**Comment by marianmajan-ibl** [comment]
I just would like to confirm that the problem with `0 02 153` is just a problem of output formatting in our tool, my colleague has debugged it and the value is correctly decoded as `94000000000` for the last BUFR.

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 in BUFR_TableD_en_21.csv and txt/BUFR_TableD_en.txt "Latitude/longitude(high accuracy)" should be "Latitude/longitude (high accuracy)" (with a space between longitude and (high)?

**Comment by amilan17** [comment]
@jitsukoh typo is fixed.

**Comment by jitsukoh** [comment]
@amilan17 thanks! I confirm that the branch is updated and I move this issue to the validated status.
